/**
 * 눈누(https://noonnu.cc/index) 상업용 무료 한글 웹폰트 메타데이터.
 * 모든 폰트는 유효한 웹폰트 URL(woff2, woff, css 등)을 갖추고 있습니다.
 */
export interface NoonnuFont {
  readonly id: string;
  readonly name: string;
  readonly cardFamily: string;
  readonly author: string;
  readonly url: string;
  readonly format?: string;
  readonly weight?: string;
}

/**
 * 눈누 글꼴 전체 메타데이터를 불러온다. 카탈로그는 별도 청크라 편집기 글꼴 목록이나
 * 무대가 처음 글꼴을 찾을 때 한 번만 받는다. 서비스 워커가 JS 청크를 모두 프리캐시하므로
 * 오프라인 송출에서도 네트워크 없이 열린다.
 */
export async function loadNoonnuFontCatalog(): Promise<readonly NoonnuFont[]> {
  const { NOONNU_FONTS } = await import("./noonnuFontCatalog");
  return NOONNU_FONTS;
}

/**
 * 스타일 스키마가 허용하는 글꼴 이름 목록 (각 글꼴의 이름과 카드 패밀리명).
 * 저장된 덱을 검증할 때 쓰므로 카탈로그와 달리 메인 번들에 남는다.
 */
export const NOONNU_SUPPORTED_FONT_NAMES: readonly [string, ...string[]] = [
  "Pretendard",
  "Noto Sans KR",
  "Nanum Myeongjo",
  "Gmarket Sans",
  "KoPubWorld Batang",
  "GmarketSansMedium",
  "고운바탕",
  "GowunBatang-Regular",
  "프리텐다드",
  "Pretendard-Regular",
  "페이퍼로지",
  "Paperlogy-8ExtraBold",
  "G마켓 산스",
  "메모먼트 꾹꾹체",
  "memomentKkukKkuk",
  "온글잎 윤탱체",
  "여기어때 잘난체",
  "yg-jalnan",
  "이서윤체",
  "LeeSeoyun",
  "어그로체",
  "SBAggroB",
  "에스코어드림",
  "S-CoreDream-3Light",
  "프리젠테이션",
  "Freesentation-9Black",
  "KoPub돋움",
  "KoPubDotumMedium",
  "제주돌담체",
  "EF_jejudoldam",
  "수트",
  "SUIT-Regular",
  "조선굴림체",
  "ChosunGu",
  "온글잎 박다현체",
  "Ownglyph_ParkDaHyun",
  "카페24 써라운드",
  "Cafe24Ssurround",
  "부크크 명조",
  "BookkMyungjo-Bd",
  "조선궁서체",
  "ChosunGs",
  "스텔라체",
  "Stellar_Serif_Bold_Condensed",
  "마루 부리",
  "MaruBuri",
  "와일드각",
  "KIMWILDgag-Bold",
  "에이투지체",
  "에이투지체-7Bold",
  "그리운 프롬솔",
  "Griun_Fromsol-Rg",
  "뒤틀림",
  "Distort-Bold",
  "주아체",
  "BMJUA",
  "이사만루",
  "GongGothicMedium",
  "온글잎 콘콘체",
  "Ownglyph_corncorn-Rg",
  "날선체",
  "NalSun-Regular",
  "그리운 국한박 오춘기 김작가",
  "GriunXHangeulOCHUNGIKIM-Regular",
  "물방울체 유정연",
  "SSRO_WaterDrop_Regular",
  "조선일보명조체",
  "Chosunilbo_myungjo",
  "서울사이버대학체",
  "서울사이버대학체M",
  "나눔스퀘어 네오",
  "NanumSquareNeoVariable",
  "꾸불림체",
  "BMkkubulimTTF-Regular",
  "원스토어 모바일POP체",
  "ONE-Mobile-POP",
  "강원교육모두체",
  "GangwonEdu_OTFBoldA",
  "리아체",
  "RiaSans-ExtraBold",
  "국민대학교 성곡 세리프",
  "KMU80SungkokSerif",
  "둥근모꼴+ Fixedsys",
  "DungGeunMo",
  "서울알림체",
  "SeoulAlrimTTF-Heavy",
  "Ok단단체",
  "OkDanDan-Bold",
  "넥슨 메이플스토리",
  "MaplestoryOTFBold",
  "온글잎 의연체",
  "Uiyeun",
  "그리운 경찰감성체",
  "Griun_PolSensibility-Rg",
  "학교안심 둥근미소",
  "HakgyoansimDunggeunmisoTTF-B",
  "리디바탕",
  "RIDIBatang",
  "여기어때 잘난체 고딕",
  "JalnanGothic",
  "신라문화체",
  "Shilla_CultureB-Bold",
  "레코체",
  "Recipekorea",
  "나눔스퀘어라운드",
  "NanumSquareRound",
  "을유1945",
  "Eulyoo1945-Regular",
  "우아한 세리프",
  "GraceSerif-Bold",
  "교보문고 손글씨 2025 이유빈",
  "KyoboHandwriting2025lyb",
  "빛의계승자체",
  "HeirofLightBold",
  "케리스 케듀체",
  "KERISKEDU_B",
  "쿠키런",
  "CookieRun-Regular",
  "평창평화체",
  "PyeongChangPeace-Bold",
  "카페24 아네모네",
  "Cafe24Ohsquare",
  "나눔바른고딕",
  "NanumBarunGothic",
  "경기천년제목",
  "Gyeonggi_Title_Medium",
  "본명조 (Source Han Serif)",
  "NotoSerifKR",
  "펴진고딕",
  "PyeojinGothic-Bold",
  "비트로 코어체",
  "Vitro_core",
  "잉크립퀴드체",
  "InkLipquid",
  "그리운 묘은흘림체",
  "Griun_MyoeunHeullim-Rg",
  "학교안심 알림장",
  "HakgyoansimAllimjangTTF-B",
  "Kopub World 돋움",
  "KoPubWorldDotumBold",
  "더잠실체",
  "TheJamsil5Bold",
  "오뮤 다예쁨체",
  "omyu_pretty",
  "티몬체",
  "TmonMonsori",
  "도현체",
  "BMDOHYEON",
  "드림흐물체",
  "DreamHeumulKR",
  "원스토어 모바일고딕 제목체",
  "ONE-Mobile-Title",
  "하이커체",
  "HiKR-ExtraBold",
  "카페24 빛나는별",
  "Cafe24Shiningstar",
  "교보손글씨 2019",
  "KyoboHand",
  "밑미 폰트",
  "Ownglyph_meetme-Rg",
  "양진체",
  "서초바탕",
  "SeochoBatang-Regular",
  "페어 큰부리새",
  "PearToucan-Regular",
  "강원교육튼튼체",
  "GangwonEduPowerExtraBoldA",
  "쫌생이체",
  "jjomsaengi-Regular",
  "CLOUD SOFA",
  "Cloudsofa_namgim-Regular",
  "정묵바위체",
  "SangSangRock",
  "D2Coding",
  "HS여름물빛체",
  "HSSummer",
  "롯데리아 촵땡겨체",
  "LOTTERIACHAB",
  "넥슨 Lv.1 고딕",
  "NEXON Lv1 Gothic OTF",
  "영월체",
  "YeongwolTTF-Regular",
  "고운돋움",
  "GowunDodum-Regular",
  "독립체",
  "Dokrip",
  "자연산스",
  "JayeonSans-Regular",
  "느림보고딕",
  "neurimboGothicRegular",
  "을지로체",
  "BMEULJIRO",
  "Cafe24 PRO SLIM",
  "Cafe24PROSlim-Bold",
  "함초롬바탕체",
  "HANBatang",
  "눈누 기초고딕",
  "NoonnuBasicGothicRegular",
  "윤초록우산어린이 만세",
  "YoonChildfundkoreaManSeh",
  "티머니 둥근바람",
  "TmoneyRoundWindExtraBold",
  "승리의 그날까지",
  "TillVictoryComes",
  "Continuous",
  "경기천년바탕",
  "Gyeonggi_Batang_Regular",
  "오이냉체",
  "EF_cucumbersalad",
  "델타글라스체",
  "DeltaGlassKR",
  "서울남산체",
  "SeoulNamsanM",
  "어비 세현체",
  "UhBeeSe_hyun",
  "온글잎 바닷바람",
  "Ownglyph_the_sea_breeze-Rg",
  "강원교육새음체",
  "GangwonEduSaeeum_OTFMediumA",
  "그리운 몽토리체",
  "Griun_Mongtori-Rg",
  "조선신명조",
  "ChosunSm",
  "Rix이누아리두리네",
  "RixInooAriDuriR",
  "조선굵은명조",
  "ChosunKm",
  "아리따부리",
  "Arita-buri-SemiBold",
  "군함이말문트였체",
  "GFCGunhamiTalks",
  "카페24 클래식타입",
  "Cafe24ClassicType-Regular",
  "서울한강체",
  "SeoulHangangM",
  "Rix열정도체",
  "RixYeoljeongdo_Regular",
  "파셜산스",
  "PartialSansKR-Regular",
  "KCC간판체",
  "KCC-Ganpan",
  "태나다체",
  "Tenada",
  "카페24 단정해",
  "Cafe24Danjunghae",
  "솔뫼 김대건체",
  "kdg_Medium",
  "TT투게더",
  "TTTogether",
  "엄마까투리체",
  "Katuri",
  "낭만있구미체",
  "GumiRomanceTTF",
  "가나초콜릿체",
  "ghanachoco",
  "ZEN SERIF",
  "ZEN-SERIF-TTF-Regular",
  "긱블 말랑이체",
  "GeekbleMalang2WOFF2",
  "KBO 다이아고딕체",
  "KBO-Dia-Gothic_bold",
  "케리스 케듀체 Line",
  "KERISKEDU_Line",
  "Neo둥근모",
  "NeoDunggeunmo",
  "그리운 옥수니 손글씨",
  "Griun_Oksooni-Rg",
  "세방고딕",
  "SEBANG_Gothic_Bold",
  "스포카 한 산스 네오",
  "SpoqaHanSansNeo-Regular",
  "가평 한석봉 큰붓",
  "GapyeongHanseokbong-Bold",
  "엘점선체",
  "엘점선체",
  "김정철명조",
  "KimjungchulMyungjo-Bold",
  "부크크 고딕",
  "BookkGothic-Bd",
  "스위트",
  "SUITE-Regular",
  "박물관문화재단클래식",
  "국립박물관문화재단클래식B",
  "도스이야기",
  "DOSIyagiMedium",
  "카페24 써라운드에어",
  "Cafe24SsurroundAir",
  "자이언츠체",
  "Giants-Bold",
  "넥슨 Lv.2 고딕",
  "NEXON Lv2 Gothic",
  "열린명조",
  "YeolrinMyeongjo-Medium",
  "땅스부대찌개체",
  "TTTtangsbudaejjigaeB",
  "한국기계연구원",
  "KIMM_Bold",
  "그리운X국한박 신고양이",
  "GriunXHangeul_Gowoon-Rg",
  "LINE Seed",
  "LINESeedKR-Bd",
  "빙그레체",
  "Binggrae",
  "코트라 볼드체",
  "KOTRA_BOLD-Bold",
  "연천 미수체",
  "cts5114_font01",
  "대충쓴준우체",
  "RFjunwooo",
  "카페24 고운밤",
  "Cafe24Oneprettynight",
  "배스킨라빈스체",
  "BRBA_B",
  "KBL점프체",
  "KBLJump_BTTF",
  "타닥타닥체",
  "TDTDTadakTadak",
  "꽃길",
  "SangSangFlowerRoad",
  "온글잎 긍정",
  "Ownglyph_positive",
  "순바탕",
  "SunBatang-Light",
  "HS봄바람체 3.0",
  "HSBombaram3_Regular",
  "조선100년체",
  "ChosunCentennial",
  "IM혜민체",
  "IM_Hyemin-Bold",
  "유한킴벌리 푸른숲체",
  "font-2-700",
  "즐거운이야기체",
  "OTEnjoystoriesBA",
  "함렛",
  "Hahmlet-Regular",
  "바른바탕체",
  "BareunBatang",
  "마포꽃섬",
  "MapoFlowerIsland",
  "수성혜정체",
  "SuseongHyejeong",
  "와구리체",
  "WAGURITTF",
  "베이글팻",
  "BagelFatOne-Regular",
  "푸라닭 젠틀 고딕",
  "PuradakGentleGothicR",
  "온글잎 류류체",
  "Ownglyph_ryurue-Rg",
  "엘리스 DX널리체",
  "YESMyoungjo-Regular",
  "코트라 희망체",
  "KOTRAHOPE",
  "HS산토끼체",
  "HS-Regular",
  "카페24 동동",
  "Cafe24Dongdong",
  "인천교육자람체",
  "iceJaram-Rg",
  "그리운X국한박 사랑스러운",
  "GriunXHangeulSarangseureoun-Regular",
  "머니그라피-라운디드",
  "Moneygraphy-Rounded",
  "런드리고딕",
  "TTLaundryGothicB",
  "창원단감아삭체",
  "CWDangamAsac-Bold",
  "던파 비트비트체",
  "bitbit",
  "KOHI배움",
  "KOHIBaeumOTF",
  "한나체Pro",
  "BMHANNAPro",
  "경복궁 수문장 제목체",
  "Sumunjang_TitleB",
  "OG 르네상스 비밀",
  "OG_Renaissance_Secret-Rg",
  "나눔바른펜",
  "NanumBarunpen",
  "문경감홍사과",
  "Mungyeong-Gamhong-Apple",
  "빙그레체II",
  "Binggrae-Two",
  "SF함박눈",
  "SF_HambakSnow",
  "학교안심 나들이",
  "HakgyoansimNadeuriTTF-B",
  "HS활공명조",
  "HSHwalkongSerif-Regular",
  "미원체",
  "Miwon",
  "교보손글씨 2020 박도연",
  "KyoboHandwriting2020A",
  "조선견고딕",
  "ChosunBg",
  "고도체",
  "Godo",
  "IBM Plex Sans",
  "IBMPlexSansKR-Regular",
  "정선아리랑체",
  "JSArirang-Regular",
  "조선굵은고딕",
  "ChosunKg",
  "도스샘물",
  "DOSSaemmul",
  "티웨이하늘체",
  "twaysky",
  "둘기마요고딕",
  "Dovemayo_gothic",
  "그리운 코코초이툰",
  "Griun_Cocochoitoon-Rg",
  "산돌국대떡볶이체",
  "SDKukdetopokki",
  "신비는일곱살",
  "SangSangShinb7",
  "Gothic A1",
  "GothicA1-Light",
  "세종글꽃체",
  "SejongGeulggot",
  "연성체",
  "BMYEONSUNG",
  "DEPARTURE_MONO",
  "DepartureMono-Regular",
  "HS집토끼체 라운드",
  "HSJiptokki-Round",
  "던파 비트비트체 v2",
  "DNFBitBitv2",
  "학교안심 별빛하늘",
  "HakgyoansimByeolbichhaneulTTF-B",
  "국민연금체",
  "NPSfontBold",
  "KCC무럭무럭체",
  "KCCMurukmuruk",
  "Kopub World 바탕",
  "KoPubWorldBatangBold",
  "날쌘돌이체",
  "CallifontSharpie-Bold",
  "기랑해랑체",
  "BMKIRANGHAERANG",
  "그리운 2019년도 아영의 손글씨",
  "Griun_AhyoungsHandwriteIn2019-Rg",
  "정선아리랑혼체",
  "JSArirangHON-Regular",
  "읏맨-궁서체",
  "OKGUNG",
  "그리운 체리한스푼",
  "GriunCherry1Spoon-Regular",
  "코레일체",
  "KorailM",
  "학교안심 우주",
  "HakgyoansimWoojuR",
  "MBC1961굴림",
  "MBC1961GulimM",
  "카페24 당당해",
  "Cafe24Dangdanghae",
  "KBL점프체 Extended",
  "KBLJump_EB_ExtendedTTF",
  "만세체",
  "Manse",
  "HS봄바람체 2.0",
  "HSBombaram",
  "HS새마을체",
  "HSSaemaul-Regular",
  "Y최애체",
  "YOnepickTTF-Bold",
  "그리운 묘은또박체",
  "Griun_Myoeunddobak-Rg",
  "엘리스디지털배움체",
  "EliceDigitalBaeum-Bd",
  "Y클로버체",
  "YClover-Bold",
  "물마루",
  "Mulmaru",
  "카카오 큰글씨",
  "KakaoBigSans-ExtraBold",
  "머니그라피-픽셀",
  "Moneygraphy-Pixel",
  "기후위기-한글",
  "ClimateCrisisKR-1979",
  "상주경천섬체",
  "SANGJUGyeongcheonIsland",
  "산하엽",
  "Diphylleia-Regular",
  "Cafe24 Loving u",
  "Cafe24Lovingu",
  "단조",
  "Danjo-bold-Regular",
  "HS산토끼체2.0",
  "HSSanTokki20-Regular",
  "웨이브 파도체",
  "WavvePADO-Regular",
  "넥슨 배찌체",
  "Bazzi",
  "동글",
  "Dongle-Regular",
  "노회찬체",
  "ROEHOE-CHAN",
  "온글잎 데이지",
  "Ownglyph_daisy-Rg",
  "투혼경남체",
  "GFCRedSpirit-Bold",
  "KBIZ한마음명조체",
  "KBIZHanmaumMyungjo",
  "포천막걸리체",
  "Makgeolli",
  "마포금빛나루",
  "MapoGoldenPier",
  "HS잔다리체",
  "HSJandari",
  "고딕 아니고 고딩",
  "Gothic_Goding",
  "산돌 삼립호빵체 Outline",
  "SDSamliphopangche_Outline",
  "영양군 음식디미방체",
  "dimibang_new",
  "오아고딕",
  "OAGothic-ExtraBold",
  "신촌랩소디체",
  "SinchonRhapsody",
  "비트로 인스파이어체",
  "VITRO-INSPIRE-TTF",
  "만화진흥원체",
  "KOMACON",
  "KBL점프체 Condensed",
  "KBLJump_EB_CondensedTTF",
  "한컴 말랑말랑",
  "HancomMalangMalang-Regular",
  "아스타산스",
  "AstaSans-Bold",
  "온글잎 김콩해",
  "Ownglyph_kimkonghae",
  "콜디웹툰메이커 온글잎 폰트",
  "Ownglyph_Coldywebtoonmaker-Rg",
  "HS봄바람체 2.1",
  "HSBombaram21-Regular",
  "국립공원 꼬미",
  "KNPSKkomi-Regular00",
  "설립체 유건욱",
  "establishRetrosansOTF",
  "학교안심 받아쓰기",
  "HakgyoansimBadasseugiTTF-L",
  "무적해병체",
  "MarinesBold",
  "그리운 규원체",
  "Griun_Gyuwon-Rg",
  "송명",
  "JSongMyung-Regular-KO",
  "상주곶감체",
  "SANJUGotgam",
  "윤초록우산어린이 민국",
  "YoonChildfundkoreaMinGuk",
  "강원교육현옥샘체",
  "GangwonEduHyeonokT_OTFMediumA",
  "월인석보체",
  "Wolin",
  "낼나 예샘체",
  "Nelna_Yesam-Rg",
  "EBS훈민정음새론체",
  "EBSHMJESaeronRA",
  "카페24슈퍼매직",
  "Cafe24Supermagic-Bold-v1.0",
  "아리따돋움",
  "Arita-dotum-Medium",
  "갈무리14",
  "Galmuri14",
  "한컴 훈민정음",
  "HancomHoonminjeongeumH",
  "온글잎 공부잘하자나",
  "Ownglyph_StudyHard-Rg",
  "완도희망체",
  "WandohopeR",
  "HS굴토끼체",
  "HSGooltokki",
  "핑크퐁 아기상어 서체",
  "TTPinkfongBabySharkR",
  "도스고딕",
  "DOSGothic",
  "학교안심 바른돋움",
  "HakgyoansimBareondotumB",
  "전기칩 한글",
  "x10y12pxDenkiChipHangul",
  "김정철손글씨",
  "KimjungchulScript-Bold",
  "던파 연단된 칼날",
  "DNFForgedBlade",
  "읏맨체",
  "OKCHAN",
  "스스로넷 손글씨체",
  "SSRONETHandwritten",
  "빙그레 싸만코체",
  "BinggraeSamanco-Bold",
  "행복고흥",
  "행복고흥L",
  "산돌 삼립호빵체 Basic",
  "SDSamliphopangche_Basic",
  "학교안심 바른바탕",
  "HakgyoansimBareonbatangB",
  "헌글",
  "Hungeul",
  "롯데리아 딱붙어체",
  "LOTTERIADDAG",
  "학교안심 지우개",
  "TTHakgyoansimJiugaeR",
  "그리운X국한박 송글손글 감성 흘림체",
  "GriunXHangeul_SongleSongeulHeullim-Rg",
  "영덕바다체",
  "YeongdeokSea",
  "휴먼범석체 네오",
  "Human-BeomseokNeoVF",
  "자이언츠체 Inline",
  "Giants-Inline",
  "학교안심 분필",
  "HakgyoansimBunpilR",
  "HS집토끼체 블랙",
  "HSJiptokki-Black",
  "Ok Mallang W",
  "OkMallangW-Regular",
  "플라이트 산스 Title",
  "FlightSans-Title",
  "태백체",
  "TAEBAEKfont",
  "KCC은영체",
  "KCC-eunyoung",
  "카페24 PRO UP",
  "Cafe24PROUP",
  "Y유니버스체",
  "YUniverse-B",
  "넥슨 워헤이븐",
  "WarhavenB",
  "대한민국 독도체",
  "Dokdo",
  "카페24 아네모네 에어",
  "Cafe24Ohsquareair",
  "델타돋움체",
  "DeltaDotumKR",
  "바른공군체",
  "ROKAFSansMedium",
  "넥슨 카트 고딕",
  "KartriderExtraBold",
  "속초바다 돋움체",
  "SokchoBadaDotum",
  "마포다카포",
  "MapoDacapo",
  "연제오방맛길체",
  "YJ_Obang",
  "민산스",
  "MinSans-Regular",
  "이순신체",
  "YiSunShinRegular",
  "귀염발랄체",
  "insungitCutelivelyjisu",
  "KBL코트체",
  "KBLCourt_EBTTF",
  "학교안심 포스터",
  "HakgyoansimPosterB",
  "윤초록우산어린이 대한",
  "YoonChildfundkoreaDaeHan",
  "그리운 경찰공평체",
  "Griun_PolFairness-Rg",
  "영도체",
  "Yeongdo-Rg",
  "PF스타더스트",
  "PFStardust",
  "전기안전체",
  "ElectricalSafetyBoldTTF",
  "그리운 겔리롤",
  "Griun_Gellyroll-Rg",
  "롯데마트드림체",
  "LotteMartDream",
  "HS여름물빛체2.0",
  "HSYeoleum20-Regular",
  "KBIZ한마음고딕체",
  "KBIZHanmaumGothic",
  "한둥근바탕",
  "WONBatang",
  "야놀자야체",
  "YanoljaYacheR",
  "추사 사랑체",
  "ChusaLove",
  "오뉴월의 꽃나무체 v.2.0 장혜리",
  "Asummerflowertree-Bold",
  "빛고을광주체",
  "Bitgoeul_Bold",
  "학교안심 그림일기",
  "HakgyoansimGeurimilgiTTF-R",
  "교보손글씨 2024 박서우",
  "KyoboHandwriting2024psw",
  "이순신돋움체",
  "YiSunShinDotumM",
  "클립아트코리아",
  "Clipartkorea-Bold",
  "감탄로드 감탄체",
  "GamtanRoadGamtanTTF",
  "송암 이형식체",
  "SongamIhyeongsik-Regular",
  "코트라 손글씨체",
  "KOTRA_SONGEULSSI",
  "영덕대게체",
  "YeongdeokSnowCrab",
  "HS유지체",
  "HSYuji-Regular",
  "닉스곤폰트",
  "NIXGONM-Vb",
  "조선가는고딕",
  "ChosunSg",
  "Y페어링체",
  "YPairingFont-Bd",
  "창원단감둥근체",
  "ChangwonDangamRound-Regular",
  "둘기마요",
  "Dovemayo-Medium",
  "학교안심 물결",
  "TTHakgyoansimMulgyeolB",
  "Ok Mallang B",
  "OkMallangB-Regular",
  "안성탕면체",
  "Ansungtangmyun-Bold",
  "미생체",
  "SDMiSaeng",
  "감탄로드 탄탄체",
  "GamtanRoadTantanTTF",
  "어비 찌바체",
  "UhBeeZZIBA-Regular",
  "정선아리랑뿌리체",
  "JSArirangPPURI-Regular",
  "을지로10년후체",
  "BMEuljiro10yearslater",
  "넥슨 풋볼고딕",
  "NEXONFootballGothicBA1",
  "마비옛체",
  "MabinogiClassicR",
  "Y 너만을 비춤체",
  "Y_Spotlight",
  "고도마음체",
  "godoMaum",
  "학교안심 칠판지우개",
  "HakgyoansimChilpanjiugaeTTF-B",
  "레베카체",
  "EF_Rebecca",
  "밀양영남루체",
  "MYYeongnamnu",
  "롯데마트행복체",
  "LotteMartHappy",
  "아임크리수진체",
  "ImcreSoojin",
  "KCC 안창호체",
  "KCC-Ahnchangho",
  "Mona12Emoji",
  "MBC1961",
  "MBC1961M",
  "국민대학교 성곡 세미세리프",
  "KMU80SungkokSemiSerif",
  "다이어리체",
  "EarlyFontDiary",
  "전주공예명조체",
  "JeonjuCraftMjB",
  "Y이드스트릿체",
  "YdestreetB",
  "국민대학교 해옹 산스",
  "KMU80HaeongSans",
  "온글잎 류뚱체",
  "Ownglyph_ryuttung-Rg",
  "해피니스 산스",
  "Happiness-Sans-Bold",
  "가석체",
  "GasoekOne-Regular",
  "그리운 오엔손글씨체",
  "Griun_OnHandwriting-Rg",
  "그리운 오미리 손글씨",
  "Griun_OMIRI-Rg",
  "신과장",
  "SangSangShin",
  "대한체",
  "Daehan-Bold",
  "마포애민",
  "MapoAgape",
  "넷마블체",
  "netmarbleB",
  "울산중구전용서체",
  "ulsanjunggu",
  "원스토어 모바일고딕 본문체",
  "ONE-Mobile-Regular",
  "KoddiUD 온고딕",
  "KoddiUDOnGothic-Regular",
  "샤우팅체",
  "Callifont-Medium",
  "함초롬체",
  "HCRDotum",
  "이랜드 나이스체",
  "ELAND_Nice_M",
  "김정철고딕",
  "KimjungchulGothic-Bold",
  "전주완판본 각체",
  "Jeonju_gakR",
  "그리운X국한박 낯선손글",
  "GriunXHangeulAForeignHand-Regular",
  "가비아 던체",
  "GabiaDunn-Regular",
  "부산체",
  "Busan",
  "마루미냐 한글",
  "x12y12pxMaruMinyaHangul",
  "평택 안보체",
  "PTAnboR",
  "나눔휴먼",
  "NanumHumanTTFBold",
  "학교안심 몽글몽글",
  "TTHakgyoansimMonggeulmonggeulR",
  "김좌진장군체",
  "GenKJwajinOTF-Rg",
  "세종학당",
  "KingSejongInstitute-Bold",
  "코트라 도약체",
  "KOTRALEAP",
  "카페24 숑숑",
  "Cafe24Syongsyong",
  "바른히피",
  "Bareun_hipi",
  "평창체",
  "PyeongChang-Bold",
  "칠곡할매 이원순체",
  "Chilgok_lws",
  "비앤빛 라식체",
  "BnviitLasik",
  "꽃집막내딸",
  "SangSangYoungestDaughter",
  "Terrarum Sans Bitmap",
  "TerrarumSansBitmap",
  "연천 허목체",
  "cts5114_font02",
  "고신고딕",
  "font-108-700",
  "학교안심 키다리풍선",
  "HakgyoansimKidaripungseonL",
  "한림명조체",
  "HallymMjo-Regular",
  "페이북 글꼴",
  "paybooc-Bold",
  "박용준투사회보체",
  "ParkYongJun",
  "펀플로생존자",
  "FUNFLOWSURVIVORKR",
  "학교안심 꼬꼬마",
  "TTHakgyoansimKkokkomaR",
  "116수박화체",
  "116watermelon",
  "바른돋움체",
  "BareunDotum",
  "62570체",
  "학교안심 어항꾸미기",
  "HakgyoansimEohangkkumigiB",
  "남양주고딕",
  "Eoe_Zno_EB",
  "한용운체",
  "HAN-YONG-UN",
  "원주체",
  "원주체 Bold",
  "나눔명조옛한글",
  "NanumMyeongjoYetHangul",
  "학교안심 반달",
  "HakgyoansimBandalL",
  "모노플렉스KR",
  "MonoplexKR-Regular",
  "Interop",
  "Brow pencil",
  "Browpencil_namgim-Regular",
  "학교안심 사물함",
  "TTHakgyoansimSamulhamR",
  "생거진천체",
  "SaenggeoJincheon",
  "KCC한빛체",
  "KCC-Hanbit",
  "신영복체",
  "TlabShin",
  "잘풀리는오늘체",
  "Jal_Onuel",
  "열린고딕",
  "YeolrinGothic-Light",
  "애터미체",
  "Atomy-Bold",
  "스터닝 산스",
  "STUNNING-Bd",
  "그리운X국한박 이꼴체",
  "GriunXHangeul_Equal-Rg",
  "강한육군",
  "ROKABold",
  "학교안심 출석부",
  "HakgyoansimChulseokbuTTF-B",
  "가람연꽃",
  "Garam",
  "I AM A PLAYER",
  "IAMAPLAYER",
  "온글잎 위씨리스트",
  "Ownglyph_wiseelist-Rg",
  "KNPS오대산체",
  "KNPSOdaesan-Regular",
  "하이틴체 최효령",
  "Lasthighteen-Bold",
  "온글잎 대롱체",
  "Ownglyph_daelong-Rg",
  "가평 물결",
  "GapyeongWave",
  "빙그레 메로나체",
  "BinggraeMelona-Bold",
  "한겨레결체",
  "Hankc",
  "도봉옛길체",
  "dobong-Medium",
  "상주해례본체",
  "SANGJUHaerye",
  "온글잎 재건사",
  "Ownglyph_JAEGEONSA-Rg",
  "구름 산스",
  "goorm-sans-bold",
  "한림고딕체",
  "HallymGothic-Regular",
  "카페24 쑥쑥",
  "Cafe24Ssukssuk",
  "사천항공체",
  "SacheonHangGong-Regular",
  "EBS훈민정음",
  "EBSHunminjeongeumSBA",
  "카카오 작은글씨",
  "KakaoSmallSans-Bold",
  "KCC안중근체",
  "KCCAhnjunggeun",
  "레페리포인트 Special Italic",
  "LeferiPoint-SpecialItalicA",
  "영남일보 구상시인체",
  "YEONGNAMNEWS_Ku_Sang",
  "감탄로드 바탕체",
  "GamtanRoadBatangBoldTTF",
  "갈무리11 Condensed",
  "Galmuri11-Condensed",
  "학교안심 가을소풍",
  "HakgyoansimGaeulsopungB",
  "고령딸기체",
  "GoryeongStrawberry",
  "Cafe24 Decobox",
  "Cafe24Decobox",
  "그리운 연이나 둥둥",
  "Griun_InaDoongdoong-Rg",
  "마포홍대프리덤",
  "MapoHongdaeFreedom",
  "MICE명조",
  "MICEMyungjo",
  "문막초 달반체",
  "MUNMAK_DALBANCHE",
  "학교안심 떡볶이",
  "HakgyoansimTTeokbokkiB",
  "학교안심 퍼즐 블랙",
  "HakgyoansimPuzzleTTF-Black",
  "학교안심 리코더",
  "TTHakgyoansimRikodeoR",
  "MOVE Sans",
  "MoveSans-Bold",
  "심경하체",
  "SimKyungha",
  "굵은둥근모",
  "BoldDungGeunMo",
  "서강체",
  "SOGANGUNIVERSITYTTF",
  "EBS주시경체",
  "EBSJSKMedium",
  "그리운X국한박 뚜레",
  "GriunXHangeulDDURAE-Regular",
  "넥센타이어",
  "NEXEN_TIRE_Bold",
  "레페리포인트",
  "LeferiPoint-BlackA",
  "전남교육바른체",
  "JNE-Bareun-TTF-Bold",
  "KCC차쌤체",
  "KCCChassam",
  "도스필기",
  "DOSPilgiMedium",
  "학교안심 별자리",
  "HakgyoansimByeoljariTTF-B",
  "학교안심 보드마카",
  "HakgyoansimBoadmarkerR",
  "Neo둥근고딕Pro",
  "NeoDunggeunmoPro-Regular",
  "어비 마이센체",
  "UhBeemysen",
  "속초바다 바탕체",
  "SokchoBadaBatang",
  "밀양아리랑체",
  "MYArirang-Medium",
  "밀양해맑은상상체",
  "MYHaemalgeunSangsang",
  "KOROAD",
  "KOROADB",
  "KCC임권택체",
  "KCCImkwontaek",
  "카페24 심플해",
  "Cafe24Simplehae",
  "한컴 울주 반구대 암각화체",
  "HancomUljuBangudae",
  "명원체",
  "Hangeuljaemin4-RegularI",
  "사물놀이체",
  "CallifontSamulnori-Medium",
  "하나서체",
  "Hana2-B",
  "학교안심 상장",
  "HakgyoansimSangjangR",
  "망고보드 또박체",
  "MangoDdobak-B",
  "하늘내린 인제체",
  "SkyblessingInjeFontTTF",
  "강한공군체",
  "ROKAFSlabSerifMedium",
  "온글잎 윤우체",
  "Yoonwoo",
  "네오현대",
  "NeoHyundaiB",
  "북엔드 바탕",
  "TTBookendBatangR",
  "예스체",
  "YES24",
  "보배섬진도체",
  "BobaesumJindoTTF",
  "상주다정다감체",
  "SANGJUDajungdagam",
  "카스퀘어코드",
  "CasquareCode1080-Bold",
  "영암월출산체",
  "YeongamWolchulsanTTF",
  "학교안심 마법사",
  "TTHakgyoansimMabeopsaR",
  "godo rounded",
  "godoRoundedR",
  "문막초 해반체",
  "MUNMAK_HAEBANCHE",
  "나눔바른고딕옛한글",
  "NanumBarunGothicYetHangul",
  "하이원 원추리 제목체",
  "high1WonchuriTitleB",
  "온글잎 은별",
  "Ownglyph_eunbyul21-Rg",
  "MICE고딕",
  "MICEGothic Bold",
  "휴먼범석체",
  "Humanbumsuk",
  "덕온공주체",
  "DeogonPrincess",
  "한글재민체",
  "Jaemin",
  "인천교육힘찬체",
  "iceHimchan-Rg",
  "완주대둔산체",
  "TTWanjudaedunsancheB",
  "Kopub 돋움 2.0",
  "KoPubDotumBold",
  "케리스 배움체",
  "KERISBAEUM_B",
  "레페리포인트 Oblique",
  "LeferiPoint-WhiteObliqueA",
  "KCC손기정체",
  "KCC-Sonkeechung",
  "마포한아름",
  "MapoPeacefull",
  "다래손글씨체",
  "drfont_daraehand",
  "교보손글씨 2021 성지영",
  "KyoboHandwriting2021sjy",
  "망고보드 별별체",
  "MangoByeolbyeol",
  "간이벽온방체",
  "Kanibuk",
  "그리운 놀토서기탱구체",
  "Griun_NoltoTAENGGU-Rg",
  "퍼즐체SUPER",
  "PuzzleSansSuper",
  "KCC도담도담체",
  "KCC-DodamdodamR",
  "티웨이항공체",
  "twayair",
  "오케이티콘체",
  "Ownglyph_okticon-Bd",
  "그리운X국한박 글방구리체",
  "GriunXHangeul_Banguri-Rg",
  "비트로 프라이드체",
  "Vitro_pride",
  "도스명조",
  "DOSMyungjo",
  "잘풀리는하루체",
  "Jal_Haru",
  "J개구쟁이",
  "JGaegujaengyi-Medium-KO",
  "Cafe24 Meongi Black",
  "Cafe24Meongi-B-v1.0",
  "고양덕양체",
  "GoyangDeogyang",
  "학교안심 마니또",
  "HakgyoansimManitoR",
  "대구동성로",
  "DaeguDongseongro-Bold",
  "타이틀체",
  "SoulTitle",
  "성동고딕",
  "SungDongGothic",
  "팔칠엠엠 일상 기울임",
  "87MMILSANG-Oblique",
  "고산자",
  "Gosanja",
  "LXGW 문해 모노",
  "LXGWWenKaiMonoKR-Light",
  "교보손글씨 2023 우선아",
  "KyoboHandwriting2023wsa",
  "디자인하우스체",
  "designhouseOTFLight00",
  "My LOTTE체",
  "MyLotteBold",
  "수박양체",
  "RixXladywatermelonR",
  "Cafe24 Meongi White",
  "Cafe24Meongi-W-v1.0",
  "시원한 설레임체",
  "seolleimcool-SemiBold",
  "읏맨-엉뚱체",
  "OKDDUNG",
  "학교안심 몽당분필",
  "HakgyoansimMondangbunfilR",
  "학교안심 모험가",
  "TTHakgyoansimMoheomgaB",
  "ylee 추억은 잠들지 않는다",
  "yleeMortalHeartImmortalMemory",
  "플라이트 산스",
  "FlightSans-Bold",
  "코트라 고딕체",
  "KOTRA_GOTHIC",
  "대구북성로",
  "DaeguBukseongro-ExtraBold",
  "Orbit",
  "Orbit-Regular",
  "로커스상상고딕",
  "locus_sangsang",
  "태-흘림",
  "TSTHlmL",
  "그리운 경찰인권체",
  "Griun_PolHumanrights-Rg",
  "한둥근돋움",
  "WONDotum",
  "피플퍼스트투쟁체",
  "PeoplefirstFightingTTF",
  "엘리스 디지털코딩체",
  "EliceDigitalBaeum_Bold",
  "온글잎 민혜체",
  "Minhye",
  "망고빙수",
  "SF_IceMango",
  "그리운 사막의 연우체",
  "Griun_YEONWOO-Rg",
  "어른아이",
  "AdultKid",
  "그리운 유리 다꾸체",
  "Griun_YuriDaggu-Rg",
  "천안꿈누리터 모두체",
  "cachildrenmodu",
  "HS두꺼비체",
  "HSDuggobi",
  "그리운 두준두준체",
  "Griun_DUJUNDUJUN-Rg",
  "한컴 산스",
  "HancomSans-Light",
  "하남다움체",
  "HANAMDAUM",
  "HS겨울눈꽃체",
  "HSGyoulnoonkot",
  "국민대학교 해옹 세미산스",
  "KMU80HaeongSemiSans",
  "학교안심 붓펜",
  "HakgyoansimButpenB",
  "고양체",
  "Goyang",
  "마초체",
  "EF_MACHO",
  "학교안심 퍼즐 아웃라인",
  "HakgyoansimPuzzleTTF-Outline",
  "[KIM] B-Class ENGLISH",
  "KIMB_ENG-BOLD",
  "가비아 마음결체",
  "GabiaMaeumgyeol",
  "온글잎 무궁체",
  "OwnglyphMoogungChae",
  "한둥근제목",
  "WONTitle",
  "카스퀘어코드 이탤릭",
  "CasquareCode1080-BoldItalic",
  "끄트머리",
  "Ggeuteumuri",
  "영주선비체",
  "YEONGJUSeonbiTTF",
  "한수원 한돋움체",
  "KHNPHD",
  "해피니스 산스 Title",
  "Happiness-Sans-Title",
  "모노플렉스Nerd Italic",
  "MonoplexKRNerd-BoldItalic",
  "경복궁 수문장 본문체",
  "Sumunjang_BodyB",
  "경북대진리체",
  "KNUTRUTHTTF",
  "온글잎 언즈체",
  "Ownglyph_UNZ-Rg",
  "갈맷글",
  "Galmetgol",
  "푸른전남체",
  "PurenJeonnam",
  "온글잎 영롱",
  "Ownglyph_brilliant-Rg",
  "말싸미815",
  "Malssami815",
  "칠백삼체 유서연",
  "establishRoomNo703OTF",
  "쿨가이",
  "CoolGuy-Medium",
  "낼나 리지체",
  "NelnaLizzyChae",
  "하루일기체 젤리펜",
  "CallifontDaynoteJellypen-Bold",
  "카페24 모야모야",
  "Cafe24Moyamoya-Regular-v1.0",
  "한글재민체3.0",
  "Hangeuljaemin4-Regular",
  "사월십육일체 약속",
  "April16th-Promise",
  "학교안심 시간표",
  "HakgyoansimSiganpyoR",
  "부산바다체",
  "BusanBada",
  "김포평화바탕",
  "GimpoBatang00",
  "Cafe24 Angbanana",
  "Cafe24Angbanana",
  "대구중구읍성",
  "DaeguJungguEubseong",
  "마포당인리발전소",
  "MapoDPPA",
  "신라고딕체",
  "Shilla_Gothic-Bold",
  "그리운 심심체",
  "Griun_Simsimche-Rg",
  "밀양아리랑고딕체",
  "MYArirang_gothic",
  "림굴",
  "Limgul12",
  "학교안심 색연필",
  "HakgyoansimSaekyeonpilR",
  "청소년체",
  "Youth",
  "서평원 꺾깎체",
  "SLEIGothicTTF",
  "레페리포인트 Special",
  "LeferiPoint-SpecialA",
  "사천우주체",
  "SacheonUju-Regular",
  "TiquiTaca",
  "TiquiTaca-Regular",
  "소요단풍체",
  "SOYOMapleBoldTTF",
  "온글잎 경영체",
  "Gyungyoung",
  "웰컴체",
  "OTWelcomeRA",
  "덕온공주옛체",
  "DeogonPrincessClassic",
  "양주별산체",
  "YangjuByeolsanA1",
  "그리운 푸하체",
  "Griun_PuhaFont-Rg",
  "이랜드 초이스체",
  "ELAND_Choice_M",
  "영주풍기인삼체",
  "YEONGJUPunggiGinsengTTF",
  "Cafe24 Decoshadow",
  "Cafe24Decoshadow",
  "영남일보 1945체",
  "YNAMNEWS-Medium",
  "학교안심 산뜻돋움",
  "HakgyoansimSantteutdotumL",
  "가물치 무료고딕",
  "AssacomFreeGothicTTF-Regular",
  "인천교육소통체",
  "iceSotong-Rg",
  "수성돋움체",
  "SuseongDotum",
  "감탄로드 돋움체",
  "GamtanRoadDotumBoldTTF",
  "손편지체",
  "Handletter",
  "수박화체",
  "EF_watermelonSalad",
  "KOHI나눔",
  "KOHINanumOTFL",
  "DW임팩타민체",
  "DWImpactamin",
  "학교안심 곧은제목",
  "HakgyoansimGodeunjemokB",
  "전남교육유나체",
  "JNE-Yuna-TTF-Regular",
  "안성탕면 ESG에코체",
  "Ansungtangmyun-ESG",
  "가비아 납작블럭체",
  "NapjakBlock",
  "학교안심 여행",
  "TTHakgyoansimYeohaengR",
  "한게임포커 폰트",
  "HangamePoker-Bold",
  "유나의 화요일",
  "TheTuesdayofYounah",
  "느릿느릿체",
  "SlowSlow",
  "우리다움체",
  "WooridaumB",
  "온글잎 보현체",
  "Bohyun",
  "Cafe24 Decoschool",
  "Cafe24Decoschool",
  "학교안심 날개",
  "HakgyoansimNalgaeR",
  "도서관체",
  "LibraryK",
  "문막초 별반체",
  "MUNMAK_BYEOLBANCHE",
  "빙그레 따옴체",
  "BinggraeTaomI",
  "청주대학교체",
  "CJU-Bold",
  "얇은둥근모",
  "ThinDungGeunMo",
  "가비아 청연체",
  "GabiaCheongyeon",
  "물마루 Mono",
  "MulmaruMono",
  "그리운 정매일체",
  "Griun_EverydayJeong-Rg",
  "마포배낭여행",
  "MapoBackpacking",
  "전주완판본 순체",
  "JeonjuSunR",
  "한글누리체",
  "HangeulNuri-Bold",
  "문화재돌봄체",
  "Dolbomche_R",
  "삼립크리미 화이트체",
  "TTSamlipCreamyWhiteR",
  "칠곡할매 김영분체",
  "Chilgok_kyb",
  "전라북도체",
  "CHONBUKL",
  "청도읍성체",
  "CHEONGDOM-Medium",
  "그리운 샥샥샥",
  "Griun_Shakshakshak-Rg",
  "월영교체",
  "Wolyeonggyo",
  "Cafe24 Nyangi White",
  "Cafe24Nyangi-W-v1.0",
  "능소화",
  "GrandifloraOne-Regular",
  "대화나눔체",
  "DAEHWA_NANUM_B",
  "ACC 어린이 마음고운체",
  "ACCchildrenheartOTF-Regular",
  "HS가을생각체",
  "HSGaeulsenggak",
  "김포평화제목",
  "GimpoTitle00",
  "움돋",
  "Umdot12",
  "카페24 모야모야 Face",
  "Cafe24Moyamoya-Face-v1.0",
  "손맛체",
  "Kim Sonmat",
  "전주공예고딕체",
  "JeonjuCraftGoR",
  "고양일산체",
  "GoyangIlsan",
  "학교안심 꽈배기",
  "TTHakgyoansimKkwabaegiR",
  "티웨이날다체",
  "twayfly",
  "예스 고딕",
  "YESGothic-Regular",
  "남양주 고딕체",
  "NYJGothicEB",
  "PF스타더스트 3.0",
  "PFStardustExtraBold",
  "Kopub 바탕 2.0",
  "KoPubBatangBold",
  "레페리베이스",
  "LeferiBaseType-RegularA",
  "학교안심 뜀틀",
  "TTHakgyoansimTtwimteulR",
  "그리운X국한박 다흘체",
  "GriunXHangeul_DAHL-Rg",
  "이숲체",
  "LeeHyunJi",
  "성동명조",
  "SungDongMyungjo",
  "구미돋움체",
  "GumiDotumTTF",
  "안될과학 약체",
  "Yak",
  "UwU체(으악체) 김륜아",
  "UwU-Regular",
  "KCC김훈체",
  "KCC-Kimhoon",
  "속초바다 손글씨체",
  "SokchoBadaCalligraphy",
  "온글잎 소피체",
  "온글잎 소피",
  "그리운X국한박 제옹체",
  "GriunXHangeul_Jeong-Rg",
  "학교안심 돋보기",
  "TTHakgyoansimDotbogiR",
  "영덕해파랑체",
  "YeongdeokHaeparang",
  "램체",
  "Ramche",
  "길벗체 Rainbow",
  "GilbeotRainbow",
  "헬스셋 조릿대체",
  "HealthsetBambooStd",
  "여주도자체",
  "YeojuCeramicTTF",
  "칠곡할매 이종희체",
  "Chilgok_ljh",
  "숙명눈꽃체",
  "SMUSnowflake-Bold",
  "Intel One Mono",
  "intelone-mono-font-family-regular",
  "달무리",
  "dalmoori",
  "전남교육또박체",
  "JNE-Ttobak-TTF-Extrabold",
  "밝은체",
  "Bright",
  "미래로글꼴",
  "MiraeroNormal",
  "사각사각",
  "Sagaksagak",
  "와일드",
  "Wild",
  "민국체",
  "Minguk-Regular",
  "11번가 고딕",
  "11StreetGothic-Kor",
  "삼국지3글꼴",
  "Sam3KRFont",
  "윤초록우산어린이",
  "YoonChildfundkorea",
  "인피니티산스",
  "InfinitySans-RegularA1",
  "한돈 삼겹살체",
  "Handon3gyeopsal600g",
  "그리운 나람체",
  "Griun_Naram-Rg",
  "완도청정바다체",
  "WandocleanseaB",
  "태백은하수체",
  "TAEBAEKmilkyway",
  "솔인써니체",
  "SolinsunnyR",
  "두넌체",
  "Donoun-Medium",
  "HS겨울눈꽃체2.0",
  "HSGyeoulNoonkott20",
  "카페24 동동 Light",
  "Cafe24DongdongLight",
  "거친둘기마요",
  "Dovemayo_wild",
  "정림사지",
  "Jeongnimsaji-R",
  "강원특별자치도체",
  "GangwonState",
  "A1 전용서체",
  "EF_AONE",
  "고성금강누리체",
  "GOSEONGGEUMGANGNURI",
  "남양주다산",
  "Eoe_YE_B",
  "어비 남소영체",
  "UhBeenamsoyoung",
  "BC카드 글꼴",
  "BCcardB",
  "HBIOS-SYS",
  "모노플렉스KR Italic",
  "MonoplexKR-Italic",
  "얇은물마루",
  "ThinMulmaru",
  "칠곡할매 추유을체",
  "Chilgok_Cye",
  "KCC혜림체",
  "KCCHyerim-Regular",
  "동그라미재단",
  "ThecircleM",
  "순악필여사",
  "SSVeryBadHandwriting",
  "학교안심 봄방학",
  "HakgyoansimBombanghakR",
  "헬스셋 고딕체",
  "HealthsetGothicLight",
  "조선로고체",
  "ChosunLo",
  "온글잎 누카",
  "Ownglyph_noocar-Rg",
  "기후위기-한글 VF",
  "ClimateCrisisKRVF",
  "양평군체",
  "3YangPyeongB",
  "하이원 원추리체",
  "high1WonchuriBodyB",
  "[김씨]손글씨",
  "[Kim]Handwriting",
  "116앵무부리",
  "116angmuburi",
  "신동엽 손글씨",
  "ShinDongYupHandwriting-R",
  "둥글둥글체 김규리",
  "Roundandround-Bold",
  "한나체 Air",
  "BMHANNAAir",
  "정선동강체",
  "JSDongkang-Regular",
  "학교안심 돌담",
  "HakgyoansimDoldamB",
  "학교안심 산뜻바탕",
  "HakgyoansimSantteutbatangL",
  "LXGW 문해",
  "LXGWWenKaiKR-Light",
  "순천체",
  "SuncheonR",
  "좋은이웃체",
  "GoodNeighbors-Good-Neighbors-Bold",
  "세종병원체",
  "SejonghospitalBold",
  "윤봉길체",
  "YUN-BONG-GIL",
  "Y콤퓨타체",
  "Ycomputer-Regular",
  "전화선체",
  "JeonHwaseon",
  "칠칠공 발사체",
  "770Balsa",
  "와글와글체",
  "WagleWagle",
  "연지체",
  "Yeonji",
  "나무정원",
  "Treegarden",
  "학교안심 구름",
  "TTHakgyoansimGureumR",
  "학교안심 투호",
  "TTHakgyoansimTuhoR",
  "한수원 한울림체",
  "KHNPHU",
  "notcliche체 이현준",
  "establishNotClicheOTF",
  "가비아 봄바람체",
  "GabiaBombaram",
  "충북대직지체",
  "CBNUJIKJI",
  "김해가야체",
  "GimhaeGayaR",
  "수성바탕체",
  "SuseongBatang",
  "PF스타더스트 3.0 S",
  "PFStardustS",
  "남양주 다산체",
  "NYJDasanB",
  "엉겅퀴체",
  "Unggungqui",
  "은평사가독서체",
  "EunpyeongSagaDogseoTitle-Regular",
  "만년설체",
  "PermanentSnow",
  "가비아 솔미체",
  "GabiaSolmee",
  "을지로오래오래체",
  "BMEuljirooraeorae",
  "정신차렷체",
  "EF_WAKEUP",
  "Cafe24 Nyangi Black",
  "Cafe24Nyangi-B-v1.0",
  "국립공원 반달이",
  "KNPSBandali-Regular00",
  "Cafe24 Behappy",
  "Cafe24Behappy",
  "어비 깡자체",
  "UhBeeKang-Ja",
  "광복 이은숙",
  "GwangbokLeeEunSuk-Regular",
  "온글잎 해솜체",
  "Hesom",
  "김남윤체",
  "KimNamyun",
  "유니 띵땅띵땅",
  "Yuni_ddingddang",
  "레몬빙수",
  "SF_IceLemon",
  "모노플렉스WideNerd Italic",
  "MonoplexKRWideNerd-BoldItalic",
  "남양주 운허체",
  "NYJUnheo",
  "개미똥꾸멍",
  "SangSangAnt",
  "독립기념관체",
  "Independence_hall",
  "가비아 고스란체",
  "GabiaGosran-Regular",
  "횡성한우체",
  "HoengseongHanu",
  "선문대체",
  "SUNMOONUNIVERSITY",
  "색동저고리체 블랙",
  "SoulSaekdongBlack_L",
  "어비 미미체",
  "UhBeeMiMi",
  "길벗체 TG",
  "GilbeotTG",
  "포천오성과한음체",
  "OSeongandHanEum",
  "법정체",
  "Beopjeong",
  "나눔고딕에코",
  "NanumGothicEcoBold",
  "그리운 왼손자비슬기루체",
  "Griun_LEFTSG-Rg",
  "가비아 흘돋체",
  "GabiaHeuldot-Regular",
  "대암 이태준체",
  "DAEAM_LEE_TAE_JOON",
  "KITA",
  "-KITA-Regular",
  "한글재민체 6.0",
  "Hangeuljaemin6TTF-Regular",
  "다시 시작해",
  "Restart",
  "교보손글씨 2022 김혜남",
  "KyoboHandwriting2022khn",
  "피플퍼스트또박체",
  "PeoplefirstNeatLoudTTF",
  "학교안심 공룡알",
  "HakgyoansimGongryongalR",
  "달서달링체",
  "DalseoDarling",
  "wingbeat체 박서빈",
  "wingbeat-Bold",
  "구미첨단산업체",
  "GumiIndustryTTF",
  "BOKEH",
  "평택 노을체",
  "PTNoeulB",
  "HS가을생각체2.0",
  "HSGaeulSenggak20",
  "나는야핵인싸체 최서연",
  "establishnaneunyahaeginsaOTF",
  "학교안심 소나기",
  "TTHakgyoansimSonagiR",
  "동국체",
  "DONGGUKUNIVERSITY",
  "마이쮸체",
  "TTCrownMychewR",
  "이야기 굵은체",
  "IyagiGGC",
  "광양햇살체",
  "GwangyangSunshineBold",
  "김제시체",
  "GIMJE",
  "학교안심 나무",
  "TTHakgyoansimNamuL",
  "온글잎 때롬체",
  "Ownglyph_ttaerom-Rg",
  "온글잎 주리손편지",
  "Ownglyph_jooreeletter-Rg",
  "광양감동체",
  "GwangyangTouching",
  "구름 산스 코드",
  "goorm-sans-code",
  "평창아름다름체",
  "평창아름다름체 Regular",
  "하늘보리체",
  "SKYBORITTF",
  "어비 혜키체",
  "UhBeeHyeki",
  "유앤피플 고딕체",
  "UNPGothicKS",
  "학교안심 운동장",
  "TTHakgyoansimUndongjangL",
  "학교안심 꾸러기",
  "HakgyoansimGgooreogiR",
  "학교안심 민들레홀씨",
  "HakgyoansimMindeulleholssiR",
  "학교안심 점심시간",
  "TTHakgyoansimJeomsimsiganB",
  "해남체",
  "HaenamFont",
  "KCC김환기체",
  "KCC-Kimhwanki",
  "학교안심 맑은날",
  "HakgyoansimMalgeunnalB",
  "김포평화고딕",
  "GimpoGothicRegular00",
  "낙원어린나무체",
  "RakwonYoungTree",
  "유니폰트",
  "EF_YOONY",
  "가비아 눌체",
  "GabiaNull-Regular",
  "마포마포나루",
  "MapoMaponaru",
  "위메프체",
  "Wemakeprice-Regular",
  "Rix할매의꽃담요",
  "RixMomsBlanketR",
  "그리운 김정원",
  "Griun_Kimjungwon-Rg",
  "온글잎 석영체",
  "Sukyung",
  "중학생",
  "Middleschool_student",
  "태백 은하수체",
  "라디오고딕",
  "EF_ladio",
  "가시가시체 백민주",
  "establishThornFontOTF",
  "태-조각",
  "TSTJktB",
  "KOFIH이종욱체",
  "KOFIHDrLEEJWTTF-B",
  "탕바",
  "Tangba12",
  "그녀-길원옥",
  "Her-Gilwonok",
  "어비 현정체",
  "UhBeeHYUNJUNG",
  "완주누리체",
  "TTWanjunuricheR",
  "학교안심 콧수염",
  "TTHakgyoansimKossuyeomR",
  "J해바라기",
  "JHaebaragi-Medium-KO",
  "그리운 고씨네",
  "Griun_Gossi-Rg",
  "암스테르담",
  "Amsterdam",
  "환경체",
  "EnvironmentR",
  "어비 슬기로운생활체",
  "UhBeeSeulvely",
  "싸락눈체",
  "SF_HailSnow",
  "116앵덕정직",
  "116angduk_honesty15",
  "Cafe24 Decoline",
  "Cafe24Decoline",
  "건축조각 보통",
  "ARCHISCULPTURE_v200",
  "ACC 어린이 하늘맑은체",
  "ACCchildrenfall",
  "예쁜 민경체",
  "Mingyung",
  "규리의 일기",
  "Kyuri_diary",
  "윤고래체",
  "YunTaemin",
  "프박 뽑았체",
  "printingboxBold",
  "피렌체",
  "EF_Firenze",
  "학교안심 오카리나",
  "HakgyoansimOcarinaR",
  "길벗체 BI",
  "GilbeotBI",
  "학교안심 은하수",
  "TTHakgyoansimEunhasuR",
  "KCC박경리체",
  "KCCPakKyongni",
  "sharppoint체 민하은",
  "Unnamed-Regular",
  "사월십육일체 생명",
  "April16th-Life",
  "미래나무",
  "Future_tree",
  "세계적인 한글",
  "Global_Hangul",
  "연일전통시장체",
  "Yeonil_TM",
  "학교안심 책갈피",
  "HakgyoansimChaekgalpiR",
  "위드라이브 전용서체",
  "wedrive",
  "대구가톨릭대학체",
  "DaeguCatholicUniversity",
  "문래러",
  "SangSangMullaelerOTF",
  "Intel One Mono Italic",
  "intelone-mono-font-family-italic",
  "학교안심 수수깡",
  "HakgyoansimSusukkangL",
  "팔칠엠엠 일상 보통",
  "87MMILSANG-Regular",
  "나눔명조에코",
  "NanumMyeongjoEcoBold",
  "소미체",
  "Somi",
  "평택 반도체",
  "PTBandocheB",
  "백의의 천사",
  "White_angel",
  "이스타체",
  "EASTARJET-Medium",
  "금면성실",
  "SSFaithfulnessOTF",
  "어비 찌빠빠체",
  "UhBeeJJIBBABBA",
  "모노플렉스Wide Italic",
  "MonoplexKRWide-BoldItalic",
  "삼육대체",
  "TTSahmyookUniversityR",
  "칠곡할매 권안자체",
  "Chilgok_Kaj",
  "밍기적체",
  "Mingijuk",
  "윈도한글",
  "WinKor",
  "달서힐링체",
  "DalseoHealingBold",
  "1973미미월드",
  "1973MimiWorldR",
  "천안꿈누리터 꿈체",
  "cachildrenkkum",
  "가비아 사이체",
  "GabiaSai-Regular",
  "엑큐",
  "exqt",
  "모이라이",
  "MoiraiOne-Regular",
  "학교안심 스케치북",
  "HakgyoansimSketchbookR",
  "오방주체",
  "Obangju",
  "한컴 울주 천전리 각석체",
  "HancomUljuCheonjeonri",
  "성실체",
  "Sungsil",
  "학교안심 자연",
  "HakgyoansimJayeonR",
  "혀니도로롱",
  "EF_hyunydororong",
  "모노플렉스WideNerd",
  "MonoplexKRWideNerd-Bold",
  "인천교육시민체",
  "iceSimin-Rg",
  "가비아 온담체",
  "GabiaOndam-Regular",
  "다행체",
  "Daheng",
  "서궁",
  "Suhgung12",
  "충북대70주년체",
  "ChungbukNationalUniversity-Regular",
  "안될과학 궤도체",
  "Unreal_science_orbit",
  "ACC 어린이 가을담은체",
  "ACCchildrensky",
  "어비 푸딩체",
  "UhBeepuding",
  "DeltaUniverse",
  "DeltaUniverse-Regular",
  "꽃내음",
  "Gootneaeum",
  "Yoon 다정",
  "YoonSDJ",
  "CROOKED",
  "모노플렉스Wide",
  "MonoplexKRWide-Bold",
  "학교안심 우산",
  "TTHakgyoansimUsanR",
  "할아버지의나눔",
  "Grandpa_sharing",
  "기쁨밝음",
  "GibbemBalgeum",
  "Yoon 지희",
  "YoonSJH",
  "유설체",
  "YooSeol",
  "금은보화",
  "Geumeunbohwa",
  "배은혜체",
  "Beeunhye",
  "평창월오개체",
  "평창월오개체 Regular",
  "온글잎 승훈체",
  "Ownglyph_Seung_Hoon-Rg",
  "모노플렉스Nerd",
  "MonoplexKRNerd-Bold",
  "KCC방정환체",
  "KCCBangJeonghwan",
  "태-으뜸",
  "TSTOtmB",
  "비씨카드 글꼴",
  "어비 동경체",
  "UhBeeDongKyung",
  "하나손글씨",
  "Hana_handwriting",
  "KCC정범체",
  "KCC-Jeongbeom",
  "아기사랑체",
  "Baby_love",
  "강인한 위로",
  "Kanginhan",
  "안될과학 유니랩장체",
  "Unilab",
  "가톨릭중앙의료원체",
  "CATHOLICMEDICALCENTER",
  "세종자으미모으미체 볼드",
  "SejongJaeumiMoeumi-Bold",
  "어비 다빈체",
  "UhBeeRice",
  "소방관의 기도",
  "Firefighter_prayer",
  "그녀-이옥선",
  "Her-Leeoksun",
  "김유이체",
  "Kimyooyee",
  "안쌍체",
  "Anssang",
  "안동이육사체",
  "ANDONG264TTF",
  "김정대2벌체",
  "KJD2Beol",
  "Cafe24 Decozoo",
  "Cafe24Decozoo",
  "60’s STRIPE",
  "60sSTRIPE",
  "온글잎 지우쏘낭",
  "Ownglyph_jiwoosonang",
  "sn별별정직",
  "snByulByul",
  "세구세구체",
  "SeguSegu-Regular",
  "어비 지민2체",
  "UhBeeGmin2",
  "온글잎 매일옥자체",
  "Ownglyph_Dailyokja-Rg",
  "효남 늘 화이팅",
  "Fighting_hyonam",
  "어비 챠밍체",
  "UhBeecharming",
  "온글잎 메모앤옥자체",
  "Ownglyph_Memo_Okja-Rg",
  "사월십육일체 안전",
  "April16th-Safety",
  "대화나눔 본문체",
  "DAEHWA_Bold",
  "장미체",
  "Rose",
  "아름드리 꽃나무",
  "Flower_tree",
  "예당체",
  "Yedang",
  "학교안심 자유시간",
  "HakgyoansimJayusiganR",
  "무궁화",
  "Mugunghwa",
  "흰꼬리수리",
  "White_kkorisuri",
  "안경잡이체",
  "FOUREYES",
  "꽃소금체",
  "FlowerSalt",
  "어비 둘둘체",
  "UhBeeDoolDool",
  "맛있는체",
  "Yammy",
  "따뜻한 작별",
  "Warm_farewell",
  "EVECondom",
  "EVECondom-Regular",
  "강부장님체",
  "Kangbujang",
  "학교안심 이어달리기",
  "HakgyoansimYieodalligiL",
  "Cafe24 Decomilk",
  "Cafe24Decomilk",
  "딸에게 엄마가",
  "mom_to_daughter",
  "혀니고딕",
  "EF_hyunygothic",
  "동화또박",
  "Fairytale_ddobak",
  "영덕블루로드체",
  "YeongdeokBlueroad",
  "우리딸 손글씨",
  "Daughter_handwriting",
  "어비 앤체",
  "UhBeeann",
  "Yoon 지영",
  "YoonSJY",
  "열아홉의 반짝임",
  "Syning_19",
  "사랑해 아들",
  "Love_son",
  "아도바 온리체",
  "adobaonlyR",
  "Yoon 세희",
  "YoonSSH",
  "고서구체",
  "Goseogu-Regular",
  "카페24 쑥쑥 Light",
  "Cafe24SsukssukLight",
  "어비 또요체",
  "UhBeeDDOYO",
  "피플퍼스트자립체",
  "PeoplefirstILTTF",
  "Yoon 민준",
  "YoonSMJ",
  "점꼴체",
  "Dot_font",
  "또박또박",
  "Ddobakddobak",
  "힘내라는 말보단",
  "Saying_tobe_strong",
  "곰신체",
  "Gomsin",
  "온글잎 빈수체",
  "Ownglyph_Binsu-Rg",
  "어비 뒤죽박죽체",
  "UhBeeGENWOO",
  "미니 손글씨",
  "Mini_handwriting",
  "몽돌",
  "Mongdol",
  "문래양조 영철체",
  "YDPCF-MullaebreweryYoungchoel-Regular",
  "기상청달콤기후체",
  "Gisangchung Dalcomgihu",
  "어비 지슉지슉체",
  "UhBeeJisyukjisyuk",
  "어비 나현체",
  "UhbeeNaHyun",
  "어비 쩡체",
  "UhBeejung",
  "어비 라미체",
  "UhBeeRami",
  "나의 아내 손글씨",
  "My_wife_writing",
  "고려글꼴",
  "Koreageulggol",
  "어비 퀸제이체",
  "UhBeeQUEENJ",
  "어비 융디체",
  "UhBeeyoongdi",
  "어비 버찌체",
  "UhBeeBEOJJI",
  "초딩희망",
  "Choding_hope",
  "오방노포체",
  "ObangNoPo",
  "대광유리",
  "Deagwang_mirror",
  "어비 똘영체",
  "UhBeeddolyoung",
  "혜준체",
  "Hyejun",
  "어비 컹컹체",
  "UhBeeKeongKeong",
  "아줌마 자유",
  "Jayoo",
  "하나되어 손글씨",
  "Become_one",
  "왼손잡이도 예뻐",
  "Pretty_Left_handed",
  "어비 류가체",
  "UhBeeRyuga",
  "어비 단순그녀체",
  "UhBeeSimplegirl",
  "어비 유종체",
  "UhBeeUJong",
  "어비 링링체",
  "UhBeeRingRing",
  "둥근인연",
  "Round_destiny",
  "아인맘 손글씨",
  "Ainmom",
  "의미있는 한글",
  "Meaningful_hanguel",
  "아빠글씨",
  "Father_handwriting",
  "어비 봉식이체",
  "UhBeeBongSik",
  "어비 하늘비체",
  "UhBeeSkyrain",
  "윈디라벤더",
  "WindyLavender",
  "Yoon 아혜",
  "YoonSAH",
  "세화체",
  "Se-hwa",
  "신혼부부",
  "Newly_married",
  "어비 바니나니체",
  "UhBeeBanynany",
  "외할머니글씨",
  "Grandma_wring",
  "어비 유진체",
  "UhBeeUZ",
  "아빠의 연애편지",
  "Father_loveletter",
  "코코체",
  "Coco",
  "마고체",
  "Mago",
  "반짝반짝 별",
  "Shining_star",
  "행복한 도비",
  "Happy_dobi",
  "범솜체",
  "Bumsom",
  "세아체",
  "Se-a",
  "어비 양나체",
  "UhBeeLovelyAN",
  "시우 귀여워",
  "Cute_siu",
  "희망누리",
  "Hope_nuri",
  "정은체",
  "Jungeun",
  "엄마사랑",
  "Love_mom",
  "Yoon 흥수",
  "YoonSHS",
  "부장님 눈치체",
  "Bujangnim_nunchi",
  "어비 율체",
  "UhBeeyul",
  "어비 문슬예체",
  "UhBeemunseulye",
  "어비 햄체",
  "UhBeeHam",
  "빵구니맘 손글씨",
  "Bbang_gunimom",
  "달의궤도",
  "Orbit_of_moon",
  "어비 은디체",
  "UhBeeeunD",
  "어비 마츠코체",
  "UhBeematsuko",
  "어비 말듀체",
  "UhBeeMardyu",
  "어비 이슬체",
  "UhBeeYiseul",
  "수줍은 대학생",
  "Shy_college_student",
  "옥비체",
  "Okbi",
  "상해찬미체",
  "Sanghea_chanmi",
  "어비 하뉴이체",
  "UhBeeHanHUEY",
  "대한민국 열사체",
  "Korea_hero",
  "어비 찌풍딩체",
  "UhBeeJjipungding",
  "어비 유진남푠체",
  "UhBeeMyHusband",
  "어비 톡기체",
  "UhBeeTokki",
  "어비 아롱체",
  "UhBeeARyong",
  "열일체",
  "Hardworking",
  "어비 미니도리체",
  "UhBeeMinidori",
  "어비 송송체",
  "UhBeesong",
  "어비 한비",
  "UhBeeHanbee",
  "어비 지영체",
  "UhBeeJiyoung",
  "어비 혜몽체",
  "UhBeehyemong",
  "혁이체",
  "Hyukee",
  "어비 위윰체",
  "UhBeeWyum",
  "나는 이겨낸다",
  "I_survive",
  "따악단단",
  "Ddakdandan",
  "어비 지글체",
  "UhBeeZIGLE",
  "어비 순수결정체",
  "UhBeeUJEONG",
  "어비 미완체",
  "UhBeeMiwan",
  "비상체",
  "Bisang",
  "어비 은경체",
  "UhBeeEUNKYUNG",
  "하람체",
  "Haram",
  "아이디어회관",
  "IdeaHwegwan",
  "북극성",
  "Polar_Star",
  "한윤체",
  "Hanyoon",
  "무진장체",
  "Mujinjang",
  "야근하는 김주임",
  "Kimjuim",
  "어비 카이루체",
  "UhBeeKairu",
  "어비 스트로베리체",
  "UhBeeStrawberry",
  "어비 베이비체",
  "UhBeebaby",
  "다채사랑",
  "Dache_love",
  "어비 조커체",
  "UhBeeJoker",
  "여름글씨",
  "Summer_letter",
  "어비 카이루장난체",
  "UhBeekairumischief",
  "어비 예희체",
  "UhBeeyehee",
  "어비 이부손체",
  "UhBeeibuson",
  "어비 토모체",
  "UhBeeTOMO",
  "진주 박경아체",
  "Parkgyunga",
  "다진체",
  "Dajin",
  "철필글씨",
  "Chulpil_writing",
  "야채장수 백금례",
  "Beakeumrye",
  "어비 채은체",
  "UhBeechae-eun",
  "어비 선홍체",
  "UhBeeSunhong",
  "노력하는 동희",
  "Hardworking_donghee",
  "어비 못된여자체",
  "UhBeewockedwoman",
  "바른정신",
  "Bareun_mental",
  "어비 얀느체",
  "UhBeeYanNeu",
  "어비 하울체",
  "UhBeeHowl",
  "자부심지우",
  "Pride_jiu",
  "어비 코르체",
  "UhBeeKOR",
  "칼국수",
  "Kalguksu",
  "잘하고 있어",
  "Doing_well",
  "어비 모토미체",
  "UhBeeMotomi",
  "어비 소윤체",
  "UhBeeSoyun",
  "버드나무",
  "Bud_tree",
  "어비 진건체",
  "UhBeeJin-gun",
  "어비 여니체",
  "UhBeeYeonie",
  "나눔스퀘어",
  "NanumSquare",
  "나눔고딕",
  "Nanum Gothic",
  "검은고딕",
  "Black Han Sans",
  "갈무리9",
  "Galmuri9",
  "갈무리11",
  "Galmuri11",
  "갈무리7",
  "Galmuri7",
  "스포카 한 산스",
  "Spoqa Han Sans",
  "한나체",
  "Hanna",
  "이롭게바탕체",
  "Iropke Batang",
  "나눔손글씨붓",
  "Nanum Brush Script",
  "나눔손글씨펜",
  "Nanum Pen Script",
  "제주고딕",
  "Jeju Gothic",
  "제주명조",
  "Jeju Myeongjo",
  "제주한라산",
  "Jeju Hallasan",
  "나눔고딕코딩",
  "Nanum Gothic Coding",
  "KoPub바탕",
  "KoPub Batang",
] as const;
