import { PRESENTATION_SHORTCUTS } from "#shared";
import { COMMON_COPY } from "./common";

const SLIDE = {
  label: "슬라이드",
  add: "새 슬라이드",
  duplicate: "슬라이드 복제",
  delete: "슬라이드 삭제",
  split: "슬라이드 나누기",
  merge: "다음 슬라이드와 합치기",
  prev: "이전 슬라이드",
  next: "다음 슬라이드",
  present: "슬라이드쇼 발표",
} as const;

const SONG = {
  title: "곡 제목",
  artistOptional: "아티스트 (선택)",
  unknownArtist: "아티스트 미상",
  untitled: "제목 없음",
  addSong: "찬양곡 추가",
  editInfo: "제목·아티스트 수정",
  newLyrics: "새 가사 입력",
  myLibrary: "내 보관함",
} as const;

export const EDITOR_COPY = {
  slide: {
    ...SLIDE,
    number: (n: number) => `${SLIDE.label} ${n}`,
    lineCount: (count: number) => `${count}줄`,
    lineUsage: (used: number, max: number) => `${used}/${max}줄`,
    pageCount: (count: number) => `${count}장`,
    addTooltip: "현재 슬라이드 뒤에 새 슬라이드 추가",
    splitShort: "나누기",
    mergeShort: "합치기",
    lastCannotDelete: "곡의 마지막 한 장은 지울 수 없습니다",
    splitAtCursor: "커서 위치에서 슬라이드를 둘로 나눕니다 (Ctrl/⌘+Enter)",
    splitInHalf: "슬라이드를 가운데에서 둘로 나눕니다",
    cannotSplit:
      "가사가 두 줄 이상이거나, 편집 중 가사 사이에 커서가 있어야 나눌 수 있습니다",
    lastInSong: "이 곡의 마지막 슬라이드입니다",
    mergeNext: "다음 슬라이드의 가사를 이 슬라이드 뒤에 붙입니다",
    mergeTooLong: (max: number) => `합치면 ${max}줄을 넘어 합칠 수 없습니다`,
    lineLimit: (lines: number, chars: number) =>
      `한 슬라이드는 ${lines}줄, 한 줄 ${chars}자까지입니다. 더 넣으려면 Ctrl/⌘+Enter로 나누세요.`,
    editLyrics: "슬라이드 가사 편집",
    lyricsPlaceholder: "가사를 입력하세요",
    emptyPlaceholder: "더블클릭하여 가사 입력",
  },
  song: {
    ...SONG,
    songFormat: "곡 서식",
    noSong: "곡 없음",
    formatTooltip: "서식은 현재 곡의 모든 슬라이드에 적용됩니다",
    menu: "곡 메뉴",
    moveUp: "위로 이동",
    moveDown: "아래로 이동",
    duplicate: "곡 복제",
    removeFromSet: "세트에서 제거",
    setOnlyNotice:
      "이 세트의 곡만 바뀝니다. 보관함의 원본은 '찬양곡 추가'에서 따로 수정할 수 있습니다.",
  },
  overflow: {
    stage:
      "이 곡에서 가장 긴 슬라이드가 화면 가장자리 여백을 넘칩니다. 글자 크기를 줄이거나 슬라이드를 나눠 보세요.",
    wrap: "현재 슬라이드의 한 줄이 텍스트 박스 폭을 넘어 자동 줄바꿈됩니다. 글자 크기를 줄이거나 박스 폭을 넓혀 보세요.",
    thumbnailWrap:
      "한 줄이 텍스트 박스 폭을 넘어 자동 줄바꿈됩니다. 글자 크기를 줄이거나 박스 폭을 넓혀 보세요.",
    thumbnailStage:
      "이 곡에서 가장 긴 슬라이드라 화면 가장자리 여백을 넘칩니다. 글자 크기를 줄이거나 슬라이드를 나눠 보세요.",
    tallestSlide: (n: number) =>
      `가장 긴 슬라이드(${n}번)가 화면 가장자리 여백을 넘칩니다. 글자 크기를 줄이거나 슬라이드를 나눠 보세요.`,
  },
  header: {
    home: "홈",
    backToList: "프레젠테이션 목록으로 돌아가기",
    file: "파일",
    titleLabel: "프레젠테이션 제목",
    editTitle: "클릭하여 제목 수정",
    sharedBy: (owner: string) => `${owner}님이 공유 · 보기 전용`,
    undo: `${COMMON_COPY.undo} (Ctrl/⌘+Z)`,
    redo: `${COMMON_COPY.redo} (Ctrl/⌘+Shift+Z)`,
    shortcuts: "단축키",
    editorShortcuts: "편집 단축키",
    presentShortcuts: "발표 송출 단축키",
    numberJumpRules: "번호 이동 규칙",
  },
  syncStatus: {
    saveFailed: "저장 실패",
    syncing: "동기화 중…",
    synced: "동기화됨",
    offline: "오프라인 · 로컬 저장됨",
    syncFailed: "동기화 실패",
    autoSaved: "자동 저장됨",
  },
  readOnly: {
    guest:
      "보기 전용으로 공유받은 세트입니다. 고치려면 로그인하고 사본을 만드세요.",
    member: "보기 전용으로 공유받은 세트입니다. 고치려면 사본을 만드세요.",
  },
  copyDialog: {
    title: (title: string) => `‘${title}’ ${COMMON_COPY.makeCopy}`,
    description:
      "사본은 내 소유의 새 세트입니다. 원본이 바뀌어도 따라 바뀌지 않습니다.",
    target: "만들 위치",
    created: `${COMMON_COPY.myDrive}에 사본을 만들었습니다`,
  },
  canvas: {
    emptyTitle: "등록된 찬양 곡 또는 슬라이드가 없습니다",
    emptyDescription:
      "새 찬양 가사를 빠른 입력으로 추가하여 프레젠테이션 제작을 시작하세요.",
    pasteNewSong: "가사 붙여넣기로 새 곡 추가",
    prev: `${SLIDE.prev} (◀)`,
    next: `${SLIDE.next} (▶)`,
    slidePosition: (current: number, total: number) =>
      `${SLIDE.label} ${current}/${total}`,
    songPosition: (current: number, total: number) => `곡 ${current}/${total}`,
    zoomOut: "캔버스 축소",
    zoomIn: "캔버스 확대",
    fitLabel: "100% 원본 맞춤",
    fit: "맞춤",
  },
  thumbnails: {
    cut: "잘라내기",
    paste: "붙여넣기",
    collapseAll: "모두 축소",
    expandAll: "모두 확장",
    expandSection: "구역 펼치기",
    collapseSection: "구역 접기",
    noSongs: "아직 곡이 없습니다.",
    addSongHint: "아래에서 찬양곡을 추가하세요.",
  },
  quickPaste: {
    title: "빠른 가사 붙여넣기",
    description:
      "가사를 붙여넣으면 빈 줄 기준으로 슬라이드가 자동 분할됩니다. 빈 줄이 없으면 2줄씩 자동 분할됩니다. (슬라이드당 최대 4줄)",
    titlePlaceholder: "곡 제목을 입력하세요 (예: 은혜로다)",
    artistLabel: "아티스트 / 작곡가",
    artistPlaceholder: "아티스트 (선택사항, 예: 손경민)",
    lyricsLabel: "가사 원문",
    lyricsPlaceholder:
      "가사를 여기에 붙여넣으세요...\n\n빈 줄로 슬라이드를 나눌 수 있으며, 4줄을 초과하면 2줄씩 자동 분할됩니다.",
    preview: "슬라이드 분할 미리보기",
    total: (count: number) => `총 ${count}장`,
    emptyPreview: "왼쪽 영역에 가사를 붙여넣으면",
    emptyPreviewLine2: "실시간으로 슬라이드가 분할되어 표시됩니다.",
    submit: "세트에 추가",
  },
  externalSearch: {
    label: "가사 검색:",
    melon: "멜론",
    bugs: "벅스",
    find: (site: string) => `${site}에서 찾기`,
    search: (site: string, query: string) => `${site}에서 '${query}' 검색`,
    needTitle: "곡 제목을 먼저 입력하세요",
  },
  picker: {
    filters: { all: COMMON_COPY.all, mine: "내 곡", shared: "공유 곡" },
    searching: "공유 라이브러리를 검색하는 중…",
    noMatch: "일치하는 찬양곡이 없습니다.",
    noShared: "아직 공유된 찬양곡이 없습니다.",
    noMine: "보관함에 찬양곡이 없습니다.",
    noSongs: "아직 등록되거나 공유된 찬양곡이 없습니다.",
    counts: (mine: number, shared: number) =>
      `내 곡 ${mine} · ${COMMON_COPY.share} ${shared}`,
    description:
      "내 보관함과 다른 교회가 공유한 찬양을 검색해 세트에 추가하거나, 새 가사를 직접 입력할 수 있습니다.",
    searchLabel: "찬양곡 검색",
    searchPlaceholder: "곡 제목, 아티스트, 가사 검색...",
    kind: "곡 종류",
    showList: "목록 보기",
    serverUnavailable:
      "공유 라이브러리에 연결하지 못했습니다 — 내 곡만 표시합니다",
    offline: "오프라인 — 내 곡만 표시합니다",
    createNew: (query: string) =>
      `${query ? `'${query}' ` : ""}새 곡으로 직접 등록하기`,
    selectSong: "곡을 선택해주세요.",
    editLibraryTitle: "보관함 곡 정보 수정",
    editPublicNotice:
      "공개한 곡이라 공유 라이브러리에도 바로 반영됩니다. 이미 세트에 넣은 곡은 바뀌지 않습니다.",
    editNotice: "이미 세트에 넣은 곡은 바뀌지 않습니다.",
    deleteTitle: "보관함에서 삭제",
    deleteMessage: (title: string) =>
      `‘${title}’ 곡을 내 보관함에서 삭제할까요? 이미 세트에 넣은 곡은 그대로 남습니다.`,
    deletePublicNote: " 공개한 곡이라 공유 라이브러리에서도 내려갑니다.",
    inLibrary: "보관함에 있음",
    slideCount: (count: number) => `${count}슬라이드`,
  },
  create: {
    title: "새 찬양 가사 직접 입력",
    description:
      "가사를 입력하면 빈 줄(엔터 2번) 기준으로 슬라이드가 자동 분할됩니다. 빈 줄이 없으면 2줄씩 자동 분할됩니다. (슬라이드당 최대 4줄)",
    titlePlaceholder: "예: 시간을 뚫고",
    artistPlaceholder: "예: WELOVE",
    lyricsLabel: "가사 원문 붙여넣기",
    lyricsPlaceholder:
      "당신은 시간을 뚫고\n이 땅 가운데 오셨네\n\n우리 없는 하늘을 원치 않아\n우리 삶에 오셨네",
    splitCount: (count: number) => `${count}개 슬라이드로 자동 분할됨`,
    submit: "보관함에 저장하고 프레젠테이션에 추가",
  },
  preview: {
    lyricsCopied: "가사 복사됨",
    copyLyrics: "가사 텍스트 복사",
    report: "신고",
    splitMarker: "[슬라이드 분할]",
    mineMeta: (artist: string, slides: number) =>
      `${artist} · 총 ${slides}개 슬라이드`,
    forkedFrom: (author: string) => ` · 원작: ${author}`,
    sharedMeta: (
      artist: string,
      slides: number,
      author: string,
      forks: number,
    ) =>
      `${artist} · 총 ${slides}개 슬라이드 · 공유: ${author} · ${COMMON_COPY.forkCount(forks)}`,
    addMine: "이 곡을 프레젠테이션에 추가",
    editInfo: "정보 수정",
    sharedBadge: "공유 찬양",
    loadingLyrics: "가사를 불러오는 중…",
    importing: "가져오는 중…",
    addOwnedCopy: "보관함의 이 곡을 프레젠테이션에 추가",
    importAndAdd: "가져와서 프레젠테이션에 추가",
  },
  ribbon: {
    background: "배경",
    backgroundTooltip: (title: string) => `곡 배경: ${title}`,
    changeBackground: "곡 배경 바꾸기",
    dim: "어둡게",
    overlayOpacity: "검정 오버레이 불투명도",
    overlayHint: "배경 위를 어둡게 덮어 가사를 잘 보이게 합니다.",
    font: "글꼴",
    fontSearch: "글꼴 검색 (1,100+종)...",
    presetFonts: "기본 글꼴",
    noonnuFonts: (count: number) => `눈누 무료 웹폰트 (${count}종)`,
    noonnuLoading: "눈누 무료 웹폰트 불러오는 중…",
    showMore: (remaining: number) => `더 보기 (${remaining}개 남음)`,
    searchResults: (count: number) => `검색 결과 (${count}개)`,
    fontSize: "글자 크기",
    fontSizeTooltip: "글자 크기 (pt)",
    fontSizeList: "글자 크기 목록",
    fontSizeUp: "글자 크기 키우기",
    fontSizeUpTooltip: "글자 크기 키우기 (Ctrl/⌘+Shift+>)",
    fontSizeDown: "글자 크기 줄이기",
    fontSizeDownTooltip: "글자 크기 줄이기 (Ctrl/⌘+Shift+<)",
    fontColor: "글자 색",
    fontColorSample: "가",
    colorPicker: "컬러피커 열기",
    colorHex: "글자 색상 hex 값",
    textShadow: "텍스트 그림자",
    shadowLevel: (label: string) => `그림자 ${label}`,
    shadowLevels: {
      none: "없음",
      soft: "은은함",
      medium: "보통",
      strong: "강함",
    },
    colors: {
      white: "화이트",
      yellow: "옐로우",
      sky: "스카이",
      mint: "민트",
      pink: "핑크",
      gray: "그레이",
      black: "블랙",
    },
    paragraph: "단락",
    align: "정렬",
    alignOptions: {
      left: "왼쪽 맞춤",
      center: "가운데 맞춤",
      right: "오른쪽 맞춤",
    },
    lineHeight: "줄 간격",
    addSlideTooltip: `${SLIDE.add} (Ctrl/⌘+M)`,
    duplicateSlideTooltip: `${SLIDE.duplicate} (Ctrl/⌘+D)`,
    deleteSlideTooltip: `${SLIDE.delete} (Delete)`,
  },
  numberJumpRules: [
    "번호는 곡이 바뀌어도 이어서 셉니다. 1곡이 5장이면 2곡 첫 장은 6번입니다.",
    "숫자를 입력한 뒤 Enter를 눌러야 이동합니다.",
    `${PRESENTATION_SHORTCUTS.BUFFER_CLEAR_TIMEOUT_MS / 1000}초 동안 입력이 없으면 입력한 번호가 지워집니다.`,
    "없는 번호는 무시합니다.",
    "입력 중인 번호는 청중 화면에 표시되지 않습니다.",
  ],
} as const;

/** 단축키 안내 팝오버의 표. 키 조합도 한국어 설명을 섞어 쓰므로 여기 둔다 */
export const SHORTCUT_GUIDE = {
  editor: [
    {
      keys: "Ctrl/⌘+Z · Ctrl/⌘+Shift+Z",
      action: `${COMMON_COPY.undo} · ${COMMON_COPY.redo}`,
    },
    { keys: "← → / PageUp · PageDown / Space", action: "이전·다음 슬라이드" },
    { keys: "Home / End", action: "세트 처음·마지막 슬라이드" },
    { keys: "더블클릭 / Enter / F2", action: "슬라이드에서 가사 직접 편집" },
    { keys: "Ctrl/⌘+Enter", action: "편집 중 커서 위치에서 슬라이드 나누기" },
    { keys: "Esc", action: "가사 편집 끝내기" },
    { keys: "Ctrl/⌘+M", action: SLIDE.add },
    { keys: "Ctrl/⌘+D", action: SLIDE.duplicate },
    { keys: "Delete", action: SLIDE.delete },
    { keys: "Ctrl/⌘·Shift+클릭", action: "슬라이드 창에서 여러 장 선택" },
    {
      keys: "Shift+↑ ↓ / Ctrl/⌘+A",
      action: "슬라이드 창에서 선택 넓히기 · 곡 전체",
    },
    {
      keys: "Ctrl/⌘+C · X · V",
      action: "슬라이드 창에서 복사 · 잘라내기 · 붙여넣기",
    },
    {
      keys: "Ctrl/⌘+↑ ↓ (+Shift)",
      action: "슬라이드 한 칸 위·아래로 (곡 처음·끝으로)",
    },
    { keys: "Enter / Backspace", action: "슬라이드 창에서 새 슬라이드 · 삭제" },
    { keys: "Ctrl/⌘+Shift+> / <", action: "글자 크기 키우기·줄이기" },
    { keys: "F5", action: SLIDE.present },
  ],
  presentation: [
    { keys: "→ / Space / PageDown", action: SLIDE.next },
    { keys: "← / PageUp", action: SLIDE.prev },
    { keys: "번호 + Enter", action: "세트 전체 N번째 슬라이드로 이동" },
    { keys: "Backspace", action: "입력 중인 마지막 숫자 지우기" },
    { keys: "B", action: "블랙아웃 켜기/끄기" },
    { keys: "H", action: "가사 숨기기 (배경 유지)" },
    { keys: "Esc", action: "전체화면 해제 (송출 종료)" },
  ],
} as const;
