import { PRESENTATION_SHORTCUTS } from "#shared";
import { COMMON_COPY } from "./common";

const SLIDE = {
  label: "슬라이드",
  add: "새 슬라이드",
  duplicate: "슬라이드 복제",
  delete: "슬라이드 삭제",
  split: "슬라이드 나누기",
  merge: "다음 슬라이드와 합치기",
  prev: "이전 슬라이드",
  next: "다음 슬라이드",
  present: "슬라이드쇼 발표",
} as const;

const SONG = {
  title: "곡 제목",
  artistOptional: "아티스트 (선택)",
  unknownArtist: "아티스트 미상",
  untitled: "제목 없음",
  addSong: "곡 추가",
  editInfo: "제목·아티스트 수정",
  newLyrics: "새 가사 입력",
  myLibrary: "내 보관함",
} as const;

const SPLIT_RULE =
  "빈 줄마다 슬라이드를 나눠요. 4줄이 넘는 단락은 2줄씩 나눠요.";
const EMPTY_SONGS = "아직 곡이 없어요";
const ADD_TO_PRESENTATION = "프레젠테이션에 추가";
const OVERFLOW_FIX = "글자를 줄이거나 슬라이드를 나눠 보세요.";

export const EDITOR_COPY = {
  slide: {
    ...SLIDE,
    number: (n: number) => `${SLIDE.label} ${n}`,
    lineUsage: (used: number, max: number) => `${used}/${max}줄`,
    pageCount: (count: number) => `${count}장`,
    addTooltip: "이 슬라이드 뒤에 새 슬라이드 추가",
    splitShort: "나누기",
    mergeShort: "합치기",
    lastCannotDelete: "곡에는 슬라이드가 한 장 이상 있어야 해요",
    splitAtCursor: "커서 위치에서 둘로 나눠요 (Ctrl/⌘+Enter)",
    splitInHalf: "슬라이드를 가운데에서 둘로 나눠요",
    cannotSplit: "가사가 두 줄 이상일 때 나눌 수 있어요",
    lastInSong: "이 곡의 마지막 슬라이드예요",
    mergeNext: "다음 슬라이드 가사를 이 슬라이드 뒤에 붙여요",
    mergeTooLong: (max: number) => `합치면 ${max}줄이 넘어서 합칠 수 없어요`,
    lineLimit: (lines: number, chars: number) =>
      `슬라이드 한 장에 ${lines}줄, 한 줄에 ${chars}자까지 쓸 수 있어요. 더 쓰려면 Ctrl/⌘+Enter로 나눠 보세요.`,
    editLyrics: "슬라이드 가사 편집",
    lyricsPlaceholder: "가사를 입력해 주세요",
    emptyPlaceholder: "더블클릭해서 가사 입력",
  },
  song: {
    ...SONG,
    songFormat: "곡 서식",
    noSong: "곡 없음",
    formatTooltip: "서식은 곡의 모든 슬라이드에 적용돼요",
    menu: "곡 메뉴",
    moveUp: "위로 이동",
    moveDown: "아래로 이동",
    duplicate: "곡 복제",
    removeFromSet: "프레젠테이션에서 빼기",
    setOnlyNotice: `이 프레젠테이션의 곡만 바뀌어요. 보관함 원본은 ‘${SONG.addSong}’에서 고칠 수 있어요.`,
  },
  overflow: {
    stage: `가장 긴 슬라이드가 화면을 넘쳐요. ${OVERFLOW_FIX}`,
    wrap: "한 줄이 글상자보다 길어서 줄이 바뀌어요. 글자를 줄이거나 글상자를 넓혀 보세요.",
    tallestSlide: (n: number) =>
      `가장 긴 슬라이드(${n}번)가 화면을 넘쳐요. ${OVERFLOW_FIX}`,
  },
  header: {
    home: "홈",
    backToList: "프레젠테이션 목록으로 돌아가기",
    file: "파일",
    titleLabel: "프레젠테이션 제목",
    editTitle: "눌러서 제목 수정",
    sharedBy: (owner: string) => `${owner}님이 공유 · 보기 전용`,
    undo: `${COMMON_COPY.undo} (Ctrl/⌘+Z)`,
    redo: `${COMMON_COPY.redo} (Ctrl/⌘+Shift+Z)`,
    shortcuts: "단축키",
    editorShortcuts: "편집 단축키",
    presentShortcuts: "송출 단축키",
    numberJumpRules: "번호 이동 규칙",
  },
  syncStatus: {
    saveFailed: "저장 실패",
    syncing: "동기화 중…",
    synced: "동기화됨",
    offline: "오프라인 · 이 기기에 저장됨",
    syncFailed: "동기화 실패",
    autoSaved: "자동 저장됨",
  },
  readOnly: {
    guest:
      "보기 전용 프레젠테이션이에요. 고치려면 로그인하고 사본을 만들어 주세요.",
    member: "보기 전용 프레젠테이션이에요. 고치려면 사본을 만들어 주세요.",
  },
  copyDialog: {
    title: (title: string) => `‘${title}’ ${COMMON_COPY.makeCopy}`,
    description:
      "사본은 내 프레젠테이션이 돼요. 원본이 바뀌어도 사본은 그대로예요.",
    target: "만들 위치",
    created: `${COMMON_COPY.myDrive}에 사본을 만들었어요`,
  },
  canvas: {
    emptyTitle: EMPTY_SONGS,
    emptyDescription: "가사를 붙여넣어 첫 곡을 추가해 보세요.",
    pasteNewSong: "가사 붙여넣어 곡 추가",
    prev: `${SLIDE.prev} (◀)`,
    next: `${SLIDE.next} (▶)`,
    slidePosition: (current: number, total: number) =>
      `${SLIDE.label} ${current}/${total}`,
    songPosition: (current: number, total: number) => `곡 ${current}/${total}`,
    zoomOut: "화면 축소",
    zoomIn: "화면 확대",
    fitLabel: "100%로 맞춤",
    fit: "맞춤",
  },
  thumbnails: {
    cut: "잘라내기",
    paste: "붙여넣기",
    collapseAll: "모두 축소",
    expandAll: "모두 확장",
    expandSection: "구역 펼치기",
    collapseSection: "구역 접기",
    noSongs: EMPTY_SONGS,
    addSongHint: "아래에서 곡을 추가해 보세요.",
  },
  externalSearch: {
    label: "가사 검색:",
    melon: "멜론",
    bugs: "벅스",
    find: (site: string) => `${site}에서 찾기`,
    search: (site: string, query: string) => `${site}에서 ‘${query}’ 검색`,
    needTitle: "곡 제목을 먼저 입력해 주세요",
  },
  picker: {
    filters: { all: COMMON_COPY.all, mine: "내 곡", shared: "공유 곡" },
    searching: "공유 라이브러리를 검색하는 중…",
    noMatch: "맞는 곡이 없어요.",
    noShared: "아직 공유된 곡이 없어요.",
    noMine: "보관함에 곡이 없어요.",
    noSongs: `${EMPTY_SONGS}.`,
    counts: (mine: number, shared: number) =>
      `내 곡 ${mine} · ${COMMON_COPY.share} ${shared}`,
    description:
      "보관함과 공유 라이브러리에서 곡을 찾아 추가하거나, 새 가사를 입력해 보세요.",
    searchLabel: "곡 검색",
    searchPlaceholder: "곡 제목, 아티스트, 가사로 검색",
    kind: "곡 종류",
    showList: "목록 보기",
    serverUnavailable: "공유 라이브러리에 연결하지 못해 내 곡만 보여요",
    offline: "오프라인이라 내 곡만 보여요",
    createNew: (query: string) => `${query ? `‘${query}’ ` : ""}새 곡으로 등록`,
    selectSong: "곡을 선택해 주세요.",
    editLibraryTitle: "보관함 곡 정보 수정",
    editPublicNotice:
      "공개한 곡이라 공유 라이브러리에도 바로 반영돼요. 프레젠테이션에 이미 넣은 곡은 바뀌지 않아요.",
    editNotice: "프레젠테이션에 이미 넣은 곡은 바뀌지 않아요.",
    deleteTitle: "보관함에서 삭제",
    deleteMessage: (title: string) =>
      `‘${title}’ 곡을 보관함에서 삭제할까요? 프레젠테이션에 이미 넣은 곡은 그대로 남아요.`,
    deletePublicNote: " 공개한 곡이라 공유 라이브러리에서도 내려가요.",
    inLibrary: "보관함에 있음",
    slideCount: (count: number) => `${count}장`,
  },
  create: {
    title: "새 곡 입력",
    description: SPLIT_RULE,
    titlePlaceholder: "예: 시간을 뚫고",
    artistPlaceholder: "예: WELOVE",
    lyricsLabel: "가사",
    lyricsPlaceholder:
      "당신은 시간을 뚫고\n이 땅 가운데 오셨네\n\n우리 없는 하늘을 원치 않아\n우리 삶에 오셨네",
    splitCount: (count: number) => `슬라이드 ${count}장으로 나눠요`,
    submit: "보관함에 저장하고 추가",
  },
  preview: {
    lyricsCopied: "가사를 복사했어요",
    copyLyrics: "가사 복사",
    report: "신고",
    splitMarker: "[슬라이드 나눔]",
    mineMeta: (artist: string, slides: number) =>
      `${artist} · 슬라이드 ${slides}장`,
    forkedFrom: (author: string) => ` · 원작: ${author}`,
    sharedMeta: (
      artist: string,
      slides: number,
      author: string,
      forks: number,
    ) =>
      `${artist} · 슬라이드 ${slides}장 · 공유: ${author} · ${COMMON_COPY.forkCount(forks)}`,
    addMine: ADD_TO_PRESENTATION,
    editInfo: "정보 수정",
    sharedBadge: "공유 곡",
    loadingLyrics: "가사를 불러오는 중…",
    importing: "가져오는 중…",
    importAndAdd: "보관함에 가져와서 추가",
  },
  ribbon: {
    background: "배경",
    backgroundTooltip: (title: string) => `곡 배경: ${title}`,
    changeBackground: "곡 배경 바꾸기",
    dim: "어둡게",
    overlayOpacity: "어둡기",
    overlayHint: "배경을 어둡게 덮어 가사가 잘 보이게 해요.",
    textBackdrop: "글자 배경",
    textBackdropOpacity: "불투명도",
    textBackdropPadding: "여백",
    textBackdropRadius: "둥글기",
    textBackdropHint: "가사 뒤에만 배경을 깔아 잘 보이게 해요.",
    font: "글꼴",
    fontSearch: "글꼴 검색",
    presetFonts: "기본 글꼴",
    noonnuFonts: (count: number) => `눈누 무료 글꼴 (${count}종)`,
    noonnuLoading: "눈누 무료 글꼴을 불러오는 중…",
    showMore: (remaining: number) => `더 보기 (${remaining}개 남음)`,
    searchResults: (count: number) => `검색 결과 (${count}개)`,
    fontSize: "글자 크기",
    fontSizeTooltip: "글자 크기 (pt)",
    fontSizeList: "글자 크기 목록",
    fontSizeUp: "글자 크기 키우기",
    fontSizeUpTooltip: "글자 크기 키우기 (Ctrl/⌘+Shift+>)",
    fontSizeDown: "글자 크기 줄이기",
    fontSizeDownTooltip: "글자 크기 줄이기 (Ctrl/⌘+Shift+<)",
    fontColor: "글자 색",
    fontColorSample: "가",
    textShadow: "글자 그림자",
    shadowLevel: (label: string) => `그림자 ${label}`,
    shadowLevels: {
      none: "없음",
      soft: "은은함",
      medium: "보통",
      strong: "강함",
    },
    palette: {
      theme: "테마 색",
      standard: "표준 색",
      lighter: (name: string, percent: number) =>
        `${name}, ${percent}% 더 밝게`,
      darker: (name: string, percent: number) =>
        `${name}, ${percent}% 더 어둡게`,
      names: {
        white: "흰색",
        black: "검정",
        tan: "황갈색",
        blueGray: "파랑-회색",
        blue: "파랑",
        orange: "주황",
        gray: "회색",
        gold: "금색",
        skyBlue: "하늘색",
        green: "녹색",
        darkRed: "진한 빨강",
        red: "빨강",
        yellow: "노랑",
        lightGreen: "연한 녹색",
        lightBlue: "연한 파랑",
        darkBlue: "진한 파랑",
        purple: "자주",
      },
    },
    paragraph: "단락",
    align: "정렬",
    alignOptions: {
      left: "왼쪽 맞춤",
      center: "가운데 맞춤",
      right: "오른쪽 맞춤",
    },
    lineHeight: "줄 간격",
    addSlideTooltip: `${SLIDE.add} (Ctrl/⌘+M)`,
    duplicateSlideTooltip: `${SLIDE.duplicate} (Ctrl/⌘+D)`,
    deleteSlideTooltip: `${SLIDE.delete} (Delete)`,
  },
  numberJumpRules: [
    "번호는 곡이 바뀌어도 이어서 세요. 1곡이 5장이면 2곡 첫 장은 6번이에요.",
    "숫자를 입력하고 Enter를 눌러야 이동해요.",
    `${PRESENTATION_SHORTCUTS.BUFFER_CLEAR_TIMEOUT_MS / 1000}초 동안 입력이 없으면 입력한 번호가 지워져요.`,
    "없는 번호는 무시해요.",
    "입력 중인 번호는 청중 화면에 보이지 않아요.",
  ],
} as const;

/** 단축키 안내 팝오버의 표. 키 조합도 한국어 설명을 섞어 쓰므로 여기 둔다 */
export const SHORTCUT_GUIDE = {
  editor: [
    {
      keys: "Ctrl/⌘+Z · Ctrl/⌘+Shift+Z",
      action: `${COMMON_COPY.undo} · ${COMMON_COPY.redo}`,
    },
    { keys: "← → / PageUp · PageDown / Space", action: "이전·다음 슬라이드" },
    { keys: "Home / End", action: "처음·마지막 슬라이드" },
    { keys: "더블클릭 / Enter / F2", action: "가사 편집" },
    { keys: "Ctrl/⌘+Enter", action: "편집 중 커서 위치에서 슬라이드 나누기" },
    { keys: "Esc", action: "가사 편집 끝내기" },
    { keys: "Ctrl/⌘+M", action: SLIDE.add },
    { keys: "Ctrl/⌘+D", action: SLIDE.duplicate },
    { keys: "Delete", action: SLIDE.delete },
    { keys: "Ctrl/⌘·Shift+클릭", action: "슬라이드 창에서 여러 장 선택" },
    {
      keys: "Shift+↑ ↓ / Ctrl/⌘+A",
      action: "슬라이드 창에서 선택 넓히기 · 곡 전체",
    },
    {
      keys: "Ctrl/⌘+C · X · V",
      action: "슬라이드 창에서 복사 · 잘라내기 · 붙여넣기",
    },
    {
      keys: "Ctrl/⌘+↑ ↓ (+Shift)",
      action: "슬라이드 한 칸 위·아래로 (곡 처음·끝으로)",
    },
    { keys: "Enter / Backspace", action: "슬라이드 창에서 새 슬라이드 · 삭제" },
    { keys: "Ctrl/⌘+Shift+> / <", action: "글자 크기 키우기·줄이기" },
    { keys: "F5", action: SLIDE.present },
  ],
  presentation: [
    { keys: "→ / Space / PageDown", action: SLIDE.next },
    { keys: "← / PageUp", action: SLIDE.prev },
    { keys: "번호 + Enter", action: "N번째 슬라이드로 이동" },
    { keys: "Backspace", action: "입력 중인 마지막 숫자 지우기" },
    { keys: "B", action: "블랙아웃 켜기/끄기" },
    { keys: "H", action: "가사 숨기기 (배경 유지)" },
    { keys: "Esc", action: "전체화면 해제 (송출 종료)" },
  ],
} as const;
