export { useNavigationBuffer } from "./useNavigationBuffer";
export { usePresentationShortcuts } from "./usePresentationShortcuts";
export {
  getActivePresentation,
  createNewPresentation,
  addDeckToPresentation,
  applyServerDocuments,
  getPresentationById,
  listPresentations,
  usePresentationList,
  usePresentationById,
  updatePresentationTitle,
  updateSongStyle,
  updateSongBackground,
  updateSongInfo,
  updateSlideLines,
  addSlideToSong,
  removeSlides,
  moveSlides,
  insertSlides,
  duplicateSlides,
  splitSlideAtCursor,
  mergeSlideWithNext,
  reorderSongs,
  removeSongFromPresentation,
  duplicateSongInPresentation,
  undo,
  redo,
  canUndo,
  canRedo,
  breakHistoryCoalescing,
  hydrateFromStorage,
  flushPendingWrites,
  removePersistedPresentation,
  movePresentation,
  renamePresentation,
  trashPresentation,
  restorePresentation,
  duplicatePresentation,
  removePresentationsLocally,
  canEditPresentation,
  replaceWithServerDocument,
  showSharedPreview,
} from "./presentationStore";
export {
  exitFullscreen,
  launchPresentation,
  editorPath,
  resolvePresentReturnPath,
  DEFAULT_PRESENT_RETURN_PATH,
  type PresentNavigate,
} from "./fullscreen";
export {
  nextPosition,
  prevPosition,
  clampPosition,
  getSlideAt,
  getTotalSlideCount,
  positionOfSlideNumber,
  slideNumberOfPosition,
  INITIAL_POSITION,
  type ProjectionPosition,
} from "./projectionState";
